/**
 * 🦚 Generated by Danphe 2 Native Engine
 * Architecture: 100% Native Samsung ThorVG Vector Canvas + LVGL Engine
 * Zero-WebView • Sub-Millisecond Native Rendering
 */

#include <iostream>
#include <vector>
#include <string>
#include <lvgl.h>

#if LV_USE_THORVG
#include <thorvg.h>
using namespace tvg;
#endif

// Dolphin Native C++ State Bridge
extern "C" {
    void danphe_init_MainScreen() {
        lv_obj_t* screen = lv_scr_act();
        lv_obj_set_style_bg_color(screen, lv_color_hex(0x090d16), LV_PART_MAIN);

#if LV_USE_THORVG
        // Initialize Samsung ThorVG Canvas
        auto canvas = SwCanvas::gen();
#endif

        // [0x14/0x13] Native Text / Label #1
        lv_obj_t* lbl_1 = lv_label_create(screen);
        lv_label_set_text(lbl_1, "Danphe Embedded Screen");
        lv_obj_set_style_text_color(lbl_1, lv_color_hex(0x38bdf8), LV_PART_MAIN);
        lv_obj_align(lbl_1, LV_ALIGN_TOP_MID, 0, 25);

        // [0x14/0x13] Native Text / Label #2
        lv_obj_t* lbl_2 = lv_label_create(screen);
        // State Reactive Key -> sys_battery_level
        lv_label_set_text(lbl_2, "[State: sys_battery_level]");
        lv_obj_set_style_text_color(lbl_2, lv_color_hex(0x38bdf8), LV_PART_MAIN);
        lv_obj_align(lbl_2, LV_ALIGN_TOP_MID, 0, 60);

        // [0x10] Native Button Component #1
        lv_obj_t* btn_1 = lv_btn_create(screen);
        lv_obj_set_size(btn_1, 180, 50);
        lv_obj_align(btn_1, LV_ALIGN_CENTER, 0, 0);
        lv_obj_set_style_bg_color(btn_1, lv_color_hex(0x0284c7), LV_PART_MAIN);
        lv_obj_set_style_radius(btn_1, 12, LV_PART_MAIN);
        lv_obj_t* btn_lbl_1 = lv_label_create(btn_1);
        lv_label_set_text(btn_lbl_1, "⚡ Activate Engine");
        lv_obj_center(btn_lbl_1);

        // [0x10] Native Button Component #2
        lv_obj_t* btn_2 = lv_btn_create(screen);
        lv_obj_set_size(btn_2, 180, 50);
        lv_obj_align(btn_2, LV_ALIGN_CENTER, 0, 60);
        lv_obj_set_style_bg_color(btn_2, lv_color_hex(0x0284c7), LV_PART_MAIN);
        lv_obj_set_style_radius(btn_2, 12, LV_PART_MAIN);
        lv_obj_t* btn_lbl_2 = lv_label_create(btn_2);
        lv_label_set_text(btn_lbl_2, "🛑 Emergency Stop");
        lv_obj_center(btn_lbl_2);

        // [0x23] Native Slider Control #1
        lv_obj_t* slider_1 = lv_slider_create(screen);
        lv_obj_set_size(slider_1, 240, 18);
        lv_obj_align(slider_1, LV_ALIGN_CENTER, 0, 150);
        lv_obj_set_style_bg_color(slider_1, lv_color_hex(0x38bdf8), LV_PART_INDICATOR);
    }
}
