#pragma once

#define THORVG_VERSION_STRING "0.15.0"
#define THORVG_SVG_LOADER_SUPPORT 1
#define THORVG_SW_ENGINE_SUPPORT 1
#define THORVG_THREAD_SUPPORT 1
#define THORVG_LOG_ENABLED 1
#define TVG_BUILD 1
