'use strict';

/**
 * 🐬 KINETIC_TEXT_256 (danphe-ui / animations)
 * Full 256 100% Unique, Non-Repeating Hardware Typography & Kinetic Motion Spectrum (0x00 - 0xFF)
 * Features S-Curve Sine Waves, Wipe Left/Right/Up/Down, Raindrop Shatter Fusion, Slides, Drops, Jumps!
 */

const KINETIC_TEXT_256 = {};

function defineTextAnim(id, name, label, cssClass, duration, category) {
    const hex = '0x' + id.toString(16).toUpperCase().padStart(2, '0');
    KINETIC_TEXT_256[id] = { id, hex, name, label, cssClass, duration, category };
}

const textCategories = [
    // ── 0: FOUNDATIONAL VIDEO & WEB ESSENTIALS (0 - 15) ──
    ['STATIC_NORMAL', 'Clean Normal Text (No Motion)', 'titan-anim-idle', '0s', 'basic'],
    ['SLIDE_IN_LEFT', 'Slide In Smoothly from Left', 'titan-anim-type-slide-left', '1.0s', 'basic'],
    ['SLIDE_IN_RIGHT', 'Slide In Smoothly from Right', 'titan-anim-type-slide-right', '1.0s', 'basic'],
    ['JUMP_FROM_BOTTOM', 'Jump / Slide Up from Bottom', 'titan-anim-type-slide-up', '1.0s', 'basic'],
    ['DROP_FROM_TOP', 'Drop Down from Top Screen', 'titan-anim-type-slide-down', '1.0s', 'basic'],
    ['DROP_BOUNCE_TOP', 'Gravity Drop Down & Rubber Bounce', 'titan-anim-type-drop-bounce', '1.2s', 'basic'],
    ['JUMP_UP_BOUNCE', 'Elastic Jump from Bottom & Settle', 'titan-anim-type-jump-bounce', '1.2s', 'basic'],
    ['SINE_S_WAVE', '🌊 S-Curve Sine Wave Moving Up & Down', 'titan-anim-type-sine-wave', '1.8s', 'basic'],
    ['WIPE_IN_RIGHT', '➡️ Wipe Reveal Left-to-Right', 'titan-anim-type-wipe-right', '1.4s', 'basic'],
    ['WIPE_IN_LEFT', '⬅️ Wipe Reveal Right-to-Left', 'titan-anim-type-wipe-left', '1.4s', 'basic'],
    ['WIPE_IN_UP', '⬆️ Wipe Reveal Bottom-to-Top', 'titan-anim-type-wipe-up', '1.4s', 'basic'],
    ['WIPE_IN_DOWN', '⬇️ Wipe Reveal Top-to-Bottom', 'titan-anim-type-wipe-down', '1.4s', 'basic'],
    ['ZOOM_IN_POP', 'Smooth Scale 0% to 100% Pop In', 'titan-anim-type-zoom-in', '0.9s', 'basic'],
    ['ZOOM_OUT_FOCUS', 'Zoom Out Focus from 200%', 'titan-anim-type-zoom-out', '1.2s', 'basic'],
    ['FADE_IN_SMOOTH', 'Smooth Opacity Fade In (0 to 1)', 'titan-anim-type-fade-up', '1.0s', 'basic'],
    ['BLUR_ZOOM_IN', 'Gaussian Blur 20px Focus In', 'titan-anim-type-blur-zoom', '1.4s', 'basic'],

    // ── 1: VIRAL SOCIAL SHORTS, CAPTIONS & REELS (16 - 31) ──
    ['RAINDROP_SHATTER_FUSION', '💧 Raindrop Impact Fall, Scatter & Magnetic Fusion', 'titan-anim-type-raindrop-shatter', '2.8s', 'fluid'],
    ['S_CURVE_SNAKE_WAVE', '🐍 S-Curve Snake Wave Undulation', 'titan-anim-type-snake-wave', '2.2s', 'fluid'],
    ['ROTATE_IN_360', '360° Spin In from Depth', 'titan-anim-type-rotate-in', '1.4s', 'basic'],
    ['SKEW_SLIDE_LEFT', 'Italic Skew Slide from Left', 'titan-anim-type-skew-left', '1.0s', 'basic'],
    ['SKEW_SLIDE_RIGHT', 'Italic Skew Slide from Right', 'titan-anim-type-skew-right', '1.0s', 'basic'],
    ['CIRCULAR_ORBIT_SPIN', '🌀 360° Rotating Circular Text Orbit Badge', 'titan-anim-type-circular-orbit', '3.0s', 'circular'],
    ['3D_CYLINDER_DRUM', '🔄 3D Cylindrical Drum Roll (Carousel X)', 'titan-anim-type-cylinder-drum', '2.4s', 'circular'],
    ['HORMOZI_POP_YELLOW', 'Alex Hormozi Viral Pop & Yellow Glow', 'titan-anim-type-karaoke-bounce', '1.0s', 'social'],
    ['MRBEAST_BOUNCE_IMPACT', 'MrBeast Bouncing Word Impact', 'titan-anim-type-stamp', '0.8s', 'social'],
    ['KARAOKE_COLOR_SWEEP', 'Karaoke Smooth Left-to-Right Lyric Fill', 'titan-anim-type-karaoke', '2.0s', 'social'],
    ['EMOJI_POP_LETTER_FLOAT', 'Emoji Pop & Kinetic Float', 'titan-anim-type-balloon', '1.2s', 'social'],
    ['STAGGER_CASCADE_DROP', 'Staggered Word Cascading Drop', 'titan-anim-type-bounce', '1.4s', 'social'],
    ['JELLO_SQUASH_STRETCH', 'Jello Elastic Squash & Stretch', 'titan-anim-rubber-squash', '0.8s', 'social'],
    ['TIKTOK_GLITCH_BOUNCE', 'TikTok Viral RGB Glitch Bounce', 'titan-anim-type-rgb', '0.9s', 'social'],
    ['PUNCHY_SNAP_ZOOM', 'Punchy Snap Zoom Focus In', 'titan-anim-type-stamp', '0.6s', 'social'],
    ['LETTER_POP_IN_STAGGER', 'Letter-by-Letter Pop In Stagger', 'titan-anim-type-bounce', '1.1s', 'social'],

    // ── 2: CODING, TERMINAL & CYBERPUNK (32 - 47) ──
    ['TERMINAL_TYPEWRITER', 'Classic Terminal Typing with Caret |', 'titan-anim-typewriter', '2.0s', 'cyber'],
    ['MATRIX_DIGITAL_DECRYPT', 'Green Matrix Digital Code Decrypt', 'titan-anim-type-decrypt', '1.4s', 'cyber'],
    ['CYBERPUNK_RGB_SPLIT', 'Cyberpunk RGB Chromatic Glitch', 'titan-anim-type-rgb', '0.8s', 'cyber'],
    ['HACKER_FAST_DECODE', 'Green Hacker Cascade Decode', 'titan-anim-type-hacker', '1.2s', 'cyber'],
    ['CRT_PHOSPHOR_SCANLINES', 'CRT Monitor Phosphor Scanlines', 'titan-anim-type-neon', '1.6s', 'cyber'],
    ['QUANTUM_BITSTREAM_JITTER', 'Quantum Bitstream Jitter', 'titan-anim-jitter', '0.4s', 'cyber'],
    ['HOLOGRAM_GLITCH_STUTTER', 'Hologram Glitch Light Stutter', 'titan-anim-glitch', '0.7s', 'cyber'],
    ['ASCII_GLYPH_SCRAMBLE', 'ASCII Matrix Glyph Scramble', 'titan-anim-type-hacker', '1.3s', 'cyber'],
    ['LASER_VECTOR_ENGRAVE', 'Laser Vector Precision Engrave', 'titan-anim-type-laser', '1.5s', 'cyber'],
    ['NEON_ELECTRIC_SPARK', 'Broadway Neon Spark & Flicker', 'titan-anim-type-neon', '1.4s', 'cyber'],
    ['CYBER_WIREFRAME_FLICKER', 'Cyber Wireframe Grid Flicker', 'titan-anim-border-cyan', '1.8s', 'cyber'],
    ['SUBATOMIC_NANITE_ASSEMBLE', 'Subatomic Nanite Molecule Assemble', 'titan-anim-type-decrypt', '1.5s', 'cyber'],
    ['HIGH_VOLTAGE_LIGHTNING', 'High-Voltage Lightning Arc Zap', 'titan-anim-type-zap', '0.8s', 'cyber'],
    ['VHS_TAPE_TEAR_GLITCH', 'Analog VHS Tape Tracking Tear', 'titan-anim-glitch', '0.9s', 'cyber'],
    ['QUANTUM_TUNNEL_TELEPORT', 'Quantum Tunneling Teleport', 'titan-anim-warp', '1.0s', 'cyber'],
    ['CYBER_HUD_RETICLE_LOCK', '3D Cyber HUD Reticle Target Lock', 'titan-anim-hud-3d', '1.8s', 'cyber'],

    // ── 3: HOLLYWOOD CINEMA & TRAILERS (48 - 63) ──
    ['CINEMATIC_TRACKING_ZOOM', 'Anamorphic Letter Tracking Expansion', 'titan-anim-type-track', '2.5s', 'cinema'],
    ['CINEMATIC_FADE_UP_DEPTH', 'Words Ascend from Deep Focus', 'titan-anim-type-fade-up', '1.4s', 'cinema'],
    ['HEAVY_STAMP_SLAM_IMPACT', '300% Stamp Slam Impact', 'titan-anim-type-stamp', '0.7s', 'cinema'],
    ['3D_BLOCK_EXTRUDE_DEPTH', 'Isometric 3D Depth Extrusion', 'titan-anim-type-extrude', '1.6s', 'cinema'],
    ['24K_GOLD_SHEEN_BEAM', 'Metallic 24K Gold Sheen Beam Reflection', 'titan-anim-type-gold', '2.2s', 'cinema'],
    ['MOLTEN_FIRE_EMBER_BURN', 'Incandescent Glowing Fire Ember Words', 'titan-anim-type-fire', '1.8s', 'cinema'],
    ['METALLIC_SILVER_CHROME', 'Brushed Metallic Silver Reflection', 'titan-anim-type-gold', '2.0s', 'cinema'],
    ['PARTICLE_SMOKE_VAPORIZE', 'Gaussian Particle Smoke Vaporize', 'titan-anim-type-smoke', '1.8s', 'cinema'],
    ['LENS_FLARE_SHIMMER_BEAM', 'Anamorphic Lens Flare Shimmer', 'titan-anim-shimmer', '2.0s', 'cinema'],
    ['BLOCKBUSTER_HORIZON_RISE', 'Blockbuster Horizon Sun Rise', 'titan-anim-type-fade-up', '1.8s', 'cinema'],
    ['ETHEREAL_GHOST_FADE', 'Ethereal Ghost Dispersion Fade', 'titan-anim-float', '2.4s', 'cinema'],
    ['SHUTTER_BLIND_SLICE', 'Vertical Shutter Blind Slice', 'titan-anim-type-3d-flip', '1.2s', 'cinema'],
    ['GLASS_SHATTER_BURST', 'Tempered Glass Shatter Blast', 'titan-anim-type-explode', '0.9s', 'cinema'],
    ['BAS_RELIEF_EMBOSS', 'Chiseled Stone Bas-Relief Emboss', 'titan-anim-type-extrude', '1.5s', 'cinema'],
    ['OBSIDIAN_MIRROR_REFLECT', 'Obsidian Dark Mirror Reflection', 'titan-anim-type-mirror', '1.6s', 'cinema'],
    ['EPIC_FOG_DISPERSION', 'Epic Atmospheric Fog Dispersion', 'titan-anim-type-smoke', '2.2s', 'cinema'],

    // ── 4: SPECTRUM, LIQUID & NEON LIGHT (64 - 79) ──
    ['LIQUID_RAINBOW_FLOW', 'Liquid Iridescent Spectrum Rainbow Flow', 'titan-anim-type-rainbow', '3.0s', 'light'],
    ['BROADWAY_NEON_BILLBOARD', 'Broadway Neon Billboard Pulse', 'titan-anim-type-neon', '1.8s', 'light'],
    ['AURORA_BOREALIS_RIBBON', 'Nordic Aurora Atmospheric Ribbon', 'titan-anim-type-aurora', '3.2s', 'light'],
    ['BIOLUMINESCENT_OCEAN', 'Bioluminescent Ocean Glow', 'titan-anim-breathe', '2.4s', 'light'],
    ['PRISMATIC_DIAMOND_GLINT', 'Prismatic Diamond Facet Glint', 'titan-anim-star-burst', '1.4s', 'light'],
    ['IRIDESCENT_PEARL_SHEEN', 'Iridescent Mother-of-Pearl Sheen', 'titan-anim-shimmer', '2.2s', 'light'],
    ['CYBER_CYAN_LASER_EDGE', 'Cyber Neon Cyan Edge Glow', 'titan-anim-border-cyan', '1.6s', 'light'],
    ['MAGENTA_SYNTHWAVE_SUN', 'Magenta Synthwave Sunset Flow', 'titan-anim-type-rainbow', '2.6s', 'light'],
    ['MOLTEN_LAVA_MAGMA_FLOW', 'Molten Volcanic Lava Magma Glow', 'titan-anim-type-fire', '2.0s', 'light'],
    ['ELECTRIC_PLASMA_FILAMENT', 'Electric Plasma Filament Corona', 'titan-anim-plasma', '2.4s', 'light'],
    ['STROBE_NEON_DISCO_PULSE', 'Strobe Disco Neon Flash Pulse', 'titan-anim-strobe', '0.4s', 'light'],
    ['ULTRAVIOLET_BLACKLIGHT', 'Ultraviolet Blacklight Phosphor', 'titan-anim-type-neon', '1.8s', 'light'],
    ['SUNSET_GOLDEN_HOUR', 'Sunset Golden Hour Warm Flow', 'titan-anim-type-gold', '2.5s', 'light'],
    ['EMERALD_MATRIX_BLOOM', 'Emerald Green Matrix Bloom', 'titan-anim-bloom', '1.8s', 'light'],
    ['OPAL_CRYSTAL_SHIFT', 'Opal Crystal Color Shift', 'titan-anim-rainbow-bar', '2.8s', 'light'],
    ['HYPERDRIVE_WHITEOUT', 'Hyperdrive Warp Whiteout Bloom', 'titan-anim-bloom', '1.6s', 'light'],

    // ── 5: 3D SPATIAL & CUBE FLIPS (80 - 95) ──
    ['3D_FLIP_CASCADE_Y', '3D Letter Cascade Flip on Y-Axis', 'titan-anim-type-3d-flip', '1.4s', '3d'],
    ['3D_TILT_CASCADE_X', '3D Perspective Tilt on X-Axis', 'titan-anim-tilt-x', '1.5s', '3d'],
    ['3D_ISOMETRIC_TILE_RISE', '3D Isometric Floor Tile Rise', 'titan-anim-type-extrude', '1.4s', '3d'],
    ['3D_CARD_TUMBLE_DROP', '3D Card Tumble Gravity Drop', 'titan-anim-flip-y', '1.2s', '3d'],
    ['3D_HEXAGON_ORIGAMI', '3D Hexagon Origami Unfold', 'titan-anim-accordion', '1.0s', '3d'],
    ['3D_SPHERE_SURFACE_WARP', '3D Sphere Surface Convex Warp', 'titan-anim-warp', '1.6s', '3d'],
    ['3D_PARALLAX_DEPTH_FLOAT', '3D Parallax Multi-Layer Depth Float', 'titan-anim-float', '2.6s', '3d'],
    ['3D_FLOATING_BLOCK_STACK', '3D Floating Block Stack Rise', 'titan-anim-type-extrude', '1.8s', '3d'],
    ['3D_TORUS_RING_WRAP', '3D Torus Geometric Ring Wrap', 'titan-anim-type-circular-orbit', '3.0s', '3d'],
    ['3D_GYRO_ORBIT_TEXT', '3D Gyroscope Gimbal Orbit', 'titan-anim-hud-3d', '2.2s', '3d'],
    ['3D_ACCORDION_UNFOLD', '3D Accordion Pleat Unfold', 'titan-anim-accordion', '1.2s', '3d'],
    ['3D_LETTER_CUBE_SPIN', '3D Letter Cube 4-Sided Spin', 'titan-anim-flip-y', '1.6s', '3d'],
    ['3D_CYLINDER_PROJECTION', '3D Curved Cylinder Projection', 'titan-anim-type-cylinder-drum', '2.0s', '3d'],
    ['3D_PYRAMID_ASCEND', '3D Stepped Pyramid Ascend', 'titan-anim-type-extrude', '1.5s', '3d'],
    ['3D_TUNNEL_ZOOM_IN', '3D Infinite Tunnel Zoom In', 'titan-anim-modal-zoom', '1.4s', '3d'],
    ['3D_HYPERSPACE_WARP_GATE', '3D Hyperspace Warp Gate Pass', 'titan-anim-warp', '1.6s', '3d'],

    // ── 6: PLAYFUL, CARTOON & ARCADE (96 - 111) ──
    ['GLOSSY_BALLOON_POP', '3D Glossy Balloon Bubble Inflation', 'titan-anim-type-balloon', '0.9s', 'cartoon'],
    ['RETRO_8BIT_ARCADE_JUMP', 'Arcade 8-Bit Pixel Stepped Jump', 'titan-anim-type-8bit', '1.1s', 'cartoon'],
    ['VEGAS_SLOT_MACHINE_ROLL', 'Vegas Casino Slot Machine Tumbler', 'titan-anim-type-slot', '1.4s', 'cartoon'],
    ['RANSOM_NOTE_STAGGER', 'Punky Cutout Ransom Note Angles', 'titan-anim-type-ransom', '1.0s', 'cartoon'],
    ['JELLO_PUDDING_JIGGLE', 'Jello Pudding Playful Jiggle', 'titan-anim-btn-jiggle', '0.7s', 'cartoon'],
    ['SPRING_TOY_COIL_BOUNCE', 'Spring Toy Slinky Coil Bounce', 'titan-anim-spring', '0.8s', 'cartoon'],
    ['CARTOON_SQUASH_IMPACT', 'Cartoon Mallet Squash & Stretch', 'titan-anim-rubber-squash', '0.6s', 'cartoon'],
    ['BUBBLE_FLOAT_AND_POP', 'Translucent Bubble Float & Pop', 'titan-anim-pop', '1.2s', 'cartoon'],
    ['CONFETTI_LETTER_BLAST', 'Party Confetti Letter Blast', 'titan-anim-type-explode', '0.9s', 'cartoon'],
    ['COMIC_ACTION_SHAKE', 'Comic Book POW Action Shake', 'titan-anim-shake', '0.5s', 'cartoon'],
    ['POPCORN_KERNEL_POP', 'Popcorn High-Velocity Kernel Pop', 'titan-anim-pop', '0.7s', 'cartoon'],
    ['TRAMPOLINE_HIGH_JUMP', 'Trampoline Acrobatic High Jump', 'titan-anim-type-bounce', '1.2s', 'cartoon'],
    ['JACK_IN_THE_BOX_SPRING', 'Jack-in-the-Box Sudden Emergence', 'titan-anim-spring', '0.7s', 'cartoon'],
    ['RUBBER_BAND_SNAP_BACK', 'Rubber Band High-Tension Snap', 'titan-anim-rubber-squash', '0.5s', 'cartoon'],
    ['CARTOON_FOOTSTEP_HOP', 'Cartoon Sneaky Footstep Hop', 'titan-anim-badge-bounce', '0.8s', 'cartoon'],
    ['DOMINO_CASCADE_TOPPLE', 'Domino Chain Reaction Cascade', 'titan-anim-type-3d-flip', '1.3s', 'cartoon'],

    // ── 7: CALLIGRAPHY, BRUSH & ARTISTIC (112 - 127) ──
    ['VECTOR_BEZIER_HANDWRITE', 'Vector Bézier Cursive Handwriting Draw', 'titan-anim-type-cursive', '2.4s', 'art'],
    ['SUMIE_INK_SPLASH', 'Japanese Ink Sumi-e Water Splash', 'titan-anim-ink-ripple', '1.4s', 'art'],
    ['BRUSH_STROKE_UNDERLINE', 'Energetic Brush Stroke Underline Draw', 'titan-anim-type-uline', '0.8s', 'art'],
    ['WATERCOLOR_BLEED_REVEAL', 'Watercolor Wet Pigment Bleed', 'titan-anim-type-wipe', '2.0s', 'art'],
    ['CHALK_BLACKBOARD_SKETCH', 'Chalk on Blackboard Scratch Draw', 'titan-anim-type-cursive', '2.2s', 'art'],
    ['CHARCOAL_DUST_REVEAL', 'Charcoal Artist Dust Particle Reveal', 'titan-anim-type-smoke', '1.8s', 'art'],
    ['SPRAY_PAINT_GRAFFITI', 'Street Spray Paint Stencil Fill', 'titan-anim-type-fade-up', '1.2s', 'art'],
    ['FOUNTAIN_PEN_NIB_FLOW', 'Fountain Pen Fluid Ink Flow', 'titan-anim-type-cursive', '2.5s', 'art'],
    ['OIL_PALETTE_KNIFE_IMPASTO', 'Oil Paint Thick Palette Knife Stroke', 'titan-anim-type-stamp', '1.1s', 'art'],
    ['PASTEL_CRAYON_SMUDGE', 'Soft Pastel Crayon Smudge Reveal', 'titan-anim-type-wipe', '1.6s', 'art'],
    ['AIRBRUSH_GRADIENT_MIST', 'Fine Airbrush Gradient Mist', 'titan-anim-shimmer', '2.0s', 'art'],
    ['GOUACHE_OPAQUE_SWIPE', 'Gouache Opaque Pigment Swipe', 'titan-anim-type-wipe', '1.4s', 'art'],
    ['WOODCUT_PRINT_STAMP', 'Vintage Woodcut Relief Block Stamp', 'titan-anim-type-stamp', '0.8s', 'art'],
    ['CALLIGRAPHIC_RIBBON_SWIRL', 'Gold Calligraphic Ribbon Swirl', 'titan-anim-type-wave', '2.4s', 'art'],
    ['GOLD_LEAF_FOIL_FLAKE', 'Artisanal Gold Leaf Foil Flake', 'titan-anim-type-gold', '2.0s', 'art'],
    ['SAND_DRAWING_WIND_BLOW', 'Sand Drawing Swept by Wind', 'titan-anim-type-smoke', '2.2s', 'art'],

    // ── 8: FLUID, LIQUIDS & WATER (128 - 143) ──
    ['SUBMERGED_WATER_RIPPLE', 'Submerged Liquid Refraction Ripples', 'titan-anim-type-water', '2.0s', 'fluid'],
    ['MERCURY_DROPLET_MERGE', 'Liquid Mercury Droplets Merge', 'titan-anim-ripple', '1.6s', 'fluid'],
    ['OCEAN_SURF_UNDULATION', 'Harmonic Ocean Surface Wave', 'titan-anim-type-wave', '2.2s', 'fluid'],
    ['RAINDROP_GLASS_DRIP', 'Raindrop Streaming Down Window Glass', 'titan-anim-dl-drop', '1.5s', 'fluid'],
    ['UNDERWATER_BUBBLE_RISE', 'Translucent Underwater Bubbles Rising', 'titan-anim-float', '2.0s', 'fluid'],
    ['MELTING_ICE_DRIP', 'Glacial Ice Melting Liquid Drip', 'titan-anim-type-water', '1.8s', 'fluid'],
    ['VISCOUS_OIL_SIPHON', 'Viscous Fluid Siphon Drain', 'titan-anim-type-vortex', '2.2s', 'fluid'],
    ['MIST_EVAPORATION_LIFT', 'Atmospheric Mist Evaporation Lift', 'titan-anim-type-smoke', '2.4s', 'fluid'],
    ['WHIRLPOOL_WATER_VORTEX', 'Oceanic Whirlpool Water Vortex', 'titan-anim-vortex', '2.0s', 'fluid'],
    ['GELATIN_LIQUID_WOBBLE', 'Gelatin Matrix Fluid Wobble', 'titan-anim-cart-wobble', '1.0s', 'fluid'],
    ['WATERFALL_RAPID_CASCADE', 'Waterfall Rapid Hydro Cascade', 'titan-anim-cascade', '1.4s', 'fluid'],
    ['RIVER_CURRENT_SURGE', 'River Flowing Current Surge', 'titan-anim-type-wave', '2.0s', 'fluid'],
    ['GEYSER_STEAM_ERUPTION', 'Volcanic Geyser Steam Eruption', 'titan-anim-type-bounce', '1.2s', 'fluid'],
    ['LIQUID_SPLASH_CROWN', 'Milk Crown High-Speed Liquid Splash', 'titan-anim-type-explode', '0.9s', 'fluid'],
    ['SLIME_STRETCH_DRIP', 'Fluorescent Slime Elastic Drip', 'titan-anim-rubber-squash', '1.2s', 'fluid'],
    ['DEWDROP_SURFACE_TENSION', 'Morning Dewdrop Surface Tension', 'titan-anim-pop', '1.0s', 'fluid'],

    // ── 9: PARTICLES, EXPLOSIONS & DISPERSE (144 - 159) ──
    ['RADIAL_PARTICLE_BLAST', 'Radial Letter Particle Shockwave Blast', 'titan-anim-type-explode', '1.0s', 'particles'],
    ['PIXEL_DISSOLVE_DISPERSE', 'Digital Pixel Dissolve & Disperse', 'titan-anim-type-smoke', '1.6s', 'particles'],
    ['SPARKLER_FIREWORK_FOUNTAIN', 'Golden Sparkler Firework Fountain', 'titan-anim-star-burst', '1.4s', 'particles'],
    ['SAND_DUNE_WIND_EROSION', 'Desert Sand Dune Wind Particle Erosion', 'titan-anim-type-smoke', '2.0s', 'particles'],
    ['SUPERNOVA_STARBURST', 'Cosmic Supernova Core Explosion', 'titan-anim-bloom', '1.8s', 'particles'],
    ['ASH_EMBER_SCATTER', 'Glowing Ash Fire Ember Scatter', 'titan-anim-type-fire', '1.8s', 'particles'],
    ['CRYSTAL_SHATTER_SHARDS', 'Quartz Crystal Shatter Shards', 'titan-anim-type-explode', '0.8s', 'particles'],
    ['MAGNETIC_PARTICLE_ATTRACT', 'Magnetic Particle Inward Attractor', 'titan-anim-magnet', '1.2s', 'particles'],
    ['CLOUD_VAPOR_DISSIPATE', 'Cumulus Cloud Vapor Dissipation', 'titan-anim-type-smoke', '2.2s', 'particles'],
    ['DIGITAL_NOISE_BLAST', 'Digital White Noise Glitch Blast', 'titan-anim-glitch', '0.7s', 'particles'],
    ['ATOMIC_FISSION_CHAIN', 'Atomic Fission Chain Reaction Split', 'titan-anim-spark', '0.9s', 'particles'],
    ['METEOR_SHOCKWAVE_BURST', 'Meteor Impact Ground Shockwave', 'titan-anim-type-stamp', '0.8s', 'particles'],
    ['STARDUST_COSMIC_DRIFT', 'Galactic Stardust Cosmic Drift', 'titan-anim-float', '3.0s', 'particles'],
    ['SONIC_BOOM_RING_EXPAND', 'Sonic Boom Expanding Mach Ring', 'titan-anim-ping', '1.2s', 'particles'],
    ['PLASMA_BURST_SCATTER', 'Solar Plasma Corona Flare Scatter', 'titan-anim-plasma', '2.2s', 'particles'],
    ['DISINTEGRATION_BEAM_RAY', 'Sci-Fi Molecular Disintegration Ray', 'titan-anim-type-decrypt', '1.5s', 'particles'],

    // ── 10: AUDIO DSP & RHYTHMIC BEATS (160 - 175) ──
    ['32BAND_FFT_EQUALIZER_JUMP', '32-Band Graphic FFT Equalizer Jump', 'titan-anim-vu-meter', '0.6s', 'audio'],
    ['20HZ_SUBWOOFER_BASS_THUMP', '20Hz Sub-Bass Subwoofer Thump', 'titan-anim-thump', '0.8s', 'audio'],
    ['OSCILLOSCOPE_LISSAJOUS', 'Oscilloscope Vector Lissajous Wave', 'titan-anim-wave', '1.2s', 'audio'],
    ['SOUNDWAVE_RIPPLE_DISPERSE', 'Acoustic Soundwave Ripple Pulse', 'titan-anim-ripple', '1.4s', 'audio'],
    ['METRONOME_TEMPO_TICK', 'Precision Quartz Metronome Tempo Tick', 'titan-anim-pendulum', '1.0s', 'audio'],
    ['SPEAKER_CONE_PUNCH_KICK', 'Studio Speaker Cone Punch Impact', 'titan-anim-type-stamp', '0.6s', 'audio'],
    ['VINYL_TURNTABLE_SCRATCH', 'Vinyl Turntable Hip-Hop Scratch', 'titan-anim-jitter', '0.5s', 'audio'],
    ['HIGH_HAT_TREBLE_SIZZLE', 'Crisp Hi-Hat Cymbals Treble Sizzle', 'titan-anim-spark', '0.4s', 'audio'],
    ['SNARE_DRUM_SNAP_ATTACK', 'Snare Drum Crisp Transient Snap', 'titan-anim-pop', '0.5s', 'audio'],
    ['SYNTH_ARPEGGIATOR_STEP', 'Analog Synthesizer Arpeggiator Step', 'titan-anim-sig-ladder', '0.8s', 'audio'],
    ['FM_FREQUENCY_WOBBLE', 'FM Synthesis Bass Frequency Wobble', 'titan-anim-type-wave', '1.4s', 'audio'],
    ['AUDIO_COMPRESSOR_PUMP', 'Audio Mastering Limiter Compressor Pump', 'titan-anim-rubber-squash', '0.8s', 'audio'],
    ['VOCAL_PITCH_VIBRATO', 'Operatic Vocal Pitch Vibrato Float', 'titan-anim-type-wave', '1.8s', 'audio'],
    ['ECHO_TAPE_DELAY_REPEAT', 'Analog Tape Echo Delay Repeater', 'titan-anim-cascade', '1.2s', 'audio'],
    ['REVERB_TAIL_DIFFUSION', 'Cathedral Acoustic Reverb Tail Diffusion', 'titan-anim-type-smoke', '2.5s', 'audio'],
    ['MASTER_VU_PEAK_OVERLOAD', 'Master Analog VU Meter Redline Peak', 'titan-anim-vu-meter', '0.5s', 'audio'],

    // ── 11: SPEED, WARP & HYPERSPACE (176 - 191) ──
    ['HYPERSPACE_VELOCITY_STREAK', 'Sci-Fi Hyperspace Velocity Streak', 'titan-anim-type-warp', '1.2s', 'speed'],
    ['SONIC_BOOM_FLASH_CONE', 'Mach-2 Sonic Boom Vapor Cone Flash', 'titan-anim-bloom', '1.0s', 'speed'],
    ['TIME_DILATION_SLOW_MO', 'Einstein Relativistic Time Dilation Slow-Mo', 'titan-anim-float', '3.0s', 'speed'],
    ['TACHYON_PARTICLE_WARP', 'Faster-Than-Light Tachyon Warp', 'titan-anim-warp', '0.8s', 'speed'],
    ['LIGHT_SPEED_MOTION_BLUR', 'Light Speed Directional Smear Blur', 'titan-anim-type-track', '1.4s', 'speed'],
    ['NITRO_BOOST_ACCELERATE', 'Nitrous Oxide Twin-Turbo Acceleration', 'titan-anim-type-stamp', '0.7s', 'speed'],
    ['HYPERSPEED_STAR_TRAILS', 'Long Exposure Hyperspeed Star Trails', 'titan-anim-shimmer', '2.0s', 'speed'],
    ['LORENTZ_CONTRACTION_SNAP', 'Lorentz Length Contraction Snap', 'titan-anim-rubber-squash', '0.6s', 'speed'],
    ['QUANTUM_JUMP_BLINK', 'Quantum Instantaneous Jump Blink', 'titan-anim-strobe', '0.4s', 'speed'],
    ['BULLET_TIME_360_ORBIT', 'Matrix 360° Bullet Time Camera Orbit', 'titan-anim-type-circular-orbit', '2.8s', 'speed'],
    ['WARP_DRIVE_SPACETIME_BEND', 'Alcubierre Warp Drive Spacetime Bend', 'titan-anim-vortex', '1.8s', 'speed'],
    ['FLASH_STEP_ANIME_TELEPORT', 'Anime Flash Step Instant Transmission', 'titan-anim-warp', '0.5s', 'speed'],
    ['AFTERIMAGE_GHOST_TRAILS', 'Multi-Layer Ghost Afterimage Trails', 'titan-anim-cascade', '1.4s', 'speed'],
    ['HYPERLOOP_MAGNETIC_SURGE', 'Hyperloop Vacuum Tube Velocity Surge', 'titan-anim-type-warp', '1.0s', 'speed'],
    ['SYNCHROTRON_SPIRAL_ACCEL', 'Synchrotron Particle Accelerator Spiral', 'titan-anim-type-spiral-vortex', '2.2s', 'speed'],
    ['PHOTON_BEAM_DASH', 'Pure Laser Photon Light Beam Dash', 'titan-anim-laser', '0.6s', 'speed'],

    // ── 12: LUXURY, MINIMALIST & EDITORIAL (192 - 207) ──
    ['SWISS_BAUHAUS_GRID_SLIDE', 'Swiss Bauhaus Modernist Grid Slide', 'titan-anim-drawer-slide', '1.2s', 'editorial'],
    ['VOGUE_HIGH_FASHION_WIPE', 'Vogue Editorial High-Fashion Wipe', 'titan-anim-type-wipe', '1.8s', 'editorial'],
    ['ARCHITECTURAL_LINE_ALIGN', 'Architectural Blueprint Line Alignment', 'titan-anim-type-uline', '1.0s', 'editorial'],
    ['MINIMALIST_MASK_REVEAL', 'Minimalist Precision Mask Reveal', 'titan-anim-type-fade-up', '1.2s', 'editorial'],
    ['SUBTLE_ELEVATION_FLOAT', 'Subtle 4px Material Elevation Float', 'titan-anim-float', '2.4s', 'editorial'],
    ['MATTE_BLACK_SATIN_SHEEN', 'Matte Black Satin Texture Sheen', 'titan-anim-shimmer', '2.2s', 'editorial'],
    ['CLEAN_HORIZONTAL_SPLIT', 'Clean Horizontal Symmetric Split', 'titan-anim-type-mirror', '1.4s', 'editorial'],
    ['SCANDINAVIAN_NEUTRAL_DRIFT', 'Nordic Neutral Minimalist Drift', 'titan-anim-float', '3.0s', 'editorial'],
    ['ELEGANT_SERIF_CROSSFADE', 'Editorial Serif High-Contrast Crossfade', 'titan-anim-type-wipe', '1.6s', 'editorial'],
    ['MONOSPACE_CODE_ELEGANCE', 'Monospace Typographic Precision', 'titan-anim-typewriter', '1.8s', 'editorial'],
    ['FINE_HAIRLINE_VECTOR_DRAW', 'Fine Hairline Vector Geometry Draw', 'titan-anim-type-uline', '1.0s', 'editorial'],
    ['MAGAZINE_EDITORIAL_FLIP', 'Glossy Magazine Editorial Page Flip', 'titan-anim-flip-y', '1.2s', 'editorial'],
    ['GALLERY_SPOTLIGHT_EMERGE', 'Art Gallery Directional Spotlight Emerge', 'titan-anim-bloom', '2.0s', 'editorial'],
    ['MUSEUM_EXHIBIT_STAND', 'Museum Exhibition Plinth Rise', 'titan-anim-type-extrude', '1.5s', 'editorial'],
    ['PLATINUM_MIRROR_GLINT', 'Polished Platinum Mirror Corner Glint', 'titan-anim-star-burst', '1.4s', 'editorial'],
    ['TIMELESS_CLASSICAL_ASCEND', 'Timeless Classical Ascending Fade', 'titan-anim-type-fade-up', '2.0s', 'editorial'],

    // ── 13: MAGIC, ETHEREAL & CELESTIAL (208 - 223) ──
    ['FAIRY_DUST_SPARKLE_SHINE', 'Golden Fairy Dust Sparkle Glitter', 'titan-anim-star-burst', '1.4s', 'magic'],
    ['CONSTELLATION_STAR_CONNECT', 'Celestial Star Constellation Connect', 'titan-anim-border-cyan', '2.2s', 'magic'],
    ['ENCHANTED_RUNIC_GLYPHS', 'Ancient Arcane Runic Glyphs Glow', 'titan-anim-type-neon', '2.0s', 'magic'],
    ['MOONLIGHT_SILVER_SHIMMER', 'Full Moon Silver Ambient Shimmer', 'titan-anim-shimmer', '2.6s', 'magic'],
    ['PHOENIX_REBIRTH_FIRE_RISE', 'Immortal Phoenix Fire Rebirth Rise', 'titan-anim-type-fire', '2.2s', 'magic'],
    ['CRYSTAL_BALL_ORACLE_HAZE', 'Mystical Crystal Ball Oracle Haze', 'titan-anim-type-smoke', '2.8s', 'magic'],
    ['NEBULA_COSMIC_DUST_SWIRL', 'Orion Nebula Cosmic Dust Swirl', 'titan-anim-type-spiral-vortex', '3.2s', 'magic'],
    ['ASTRAL_PROJECTION_LEVITATE', 'Astral Projection Soul Levitation', 'titan-anim-float', '3.0s', 'magic'],
    ['MAGIC_WAND_SPARKLE_TRAIL', 'Magic Wand Glowing Spark Trail', 'titan-anim-spark', '1.2s', 'magic'],
    ['ARCANE_CIRCLE_SUMMON_SPIN', 'Arcane Summoning Circle 3D Spin', 'titan-anim-type-circular-orbit', '2.8s', 'magic'],
    ['STARFALL_METEOR_SHOWER', 'Perseid Meteor Shower Starfall', 'titan-anim-dl-drop', '1.6s', 'magic'],
    ['WITCHCRAFT_POTION_CAULDRON', 'Witchcraft Cauldron Bubbling Vapor', 'titan-anim-type-water', '2.0s', 'magic'],
    ['AURORA_CHIME_GLIMMER', 'Harmonic Aurora Wind Chime Glimmer', 'titan-anim-type-aurora', '3.0s', 'magic'],
    ['DIVINE_LIGHT_BEAM_DESCENT', 'Divine Pillar of Light Descent', 'titan-anim-bloom', '2.2s', 'magic'],
    ['TELEPATHIC_MIND_PULSE', 'Telepathic Mind Wave Pulse Ring', 'titan-anim-ping', '1.5s', 'magic'],
    ['COSMIC_PORTAL_SINGULARITY', 'Interdimensional Portal Singularity', 'titan-anim-vortex', '2.4s', 'magic'],

    // ── 14: RETRO GLITCH & 90s VHS (224 - 239) ──
    ['VHS_TRACKING_HEAD_ERROR', 'Analog VHS Tape Tracking Error Glitch', 'titan-anim-glitch', '0.8s', 'retro'],
    ['90S_TV_STATIC_WHITE_NOISE', '90s CRT TV Static White Noise', 'titan-anim-strobe', '0.5s', 'retro'],
    ['CASSETTE_TAPE_REWIND_WHIRR', 'Cassette Magnetic Tape Rewind Whirr', 'titan-anim-type-slot', '1.0s', 'retro'],
    ['CRT_CATHODE_POWER_OFF_DOT', 'Cathode Tube Shutdown Center Dot', 'titan-anim-pop', '0.7s', 'retro'],
    ['SNES_MODE7_AFFINE_WARP', '16-Bit Super Nintendo Mode-7 Warp', 'titan-anim-type-cylinder-drum', '2.0s', 'retro'],
    ['Y2K_CHROME_LIQUID_MERCURY', 'Y2K Cyber Millennium Liquid Chrome', 'titan-anim-type-gold', '2.2s', 'retro'],
    ['DITHERING_PIXEL_DEGRADE', 'Low-Bit Dithering Pixelate Degrade', 'titan-anim-type-8bit', '1.2s', 'retro'],
    ['ANALOG_COLOR_BLEED_SMEAR', 'Analog Composite NTSC Color Bleed', 'titan-anim-type-rgb', '1.0s', 'retro'],
    ['PHOSPHOR_SCREEN_BURN_GHOST', 'Green Phosphor Screen Burn Ghost', 'titan-anim-type-hacker', '1.8s', 'retro'],
    ['GLITCH_ARTIFACT_TEAR', 'MPEG Digital Artifact Macroblock Tear', 'titan-anim-glitch', '0.6s', 'retro'],
    ['FLOPPY_DISK_STEPPER_JITTER', '3.5" Floppy Disk Drive Stepper Jitter', 'titan-anim-jitter', '0.6s', 'retro'],
    ['GAMEBOY_DOT_MATRIX_GREEN', 'Original 1989 Game Boy Dot Matrix Green', 'titan-anim-type-8bit', '1.0s', 'retro'],
    ['CYBERPUNK_SUBTITLE_STUTTER', 'Neon Cyberpunk Subtitle Stutter', 'titan-anim-type-neon', '1.4s', 'retro'],
    ['90S_RAVE_STROBE_CYBER', '90s Acid Rave Strobe Neon', 'titan-anim-strobe', '0.4s', 'retro'],
    ['VHS_PAUSE_JITTER_LINE', 'VHS VCR Pause Head Jitter Line', 'titan-anim-lock-error', '0.5s', 'retro'],
    ['VINTAGE_FILM_REEL_FLICKER', '1920s Silent Film Hand-Cranked Flicker', 'titan-anim-torch', '1.2s', 'retro'],

    // ── 15: GRAND FINALE & SIGNATURE MASTER SUITE (240 - 255) ──
    ['DANPHE_SAPPHIRE_MASTER', '🐬 Danphe Blue Sapphire Master Crest', 'titan-anim-border-cyan', '2.5s', 'master'],
    ['ROYAL_DIAMOND_PRISM_STAR', 'Royal Diamond Prismatic Star Burst', 'titan-anim-star-burst', '1.8s', 'master'],
    ['HYPER_3D_CHROME_MERCURY', 'Hyper-Realistic 3D Chrome Mercury Morph', 'titan-anim-type-gold', '2.4s', 'master'],
    ['GRAND_CINEMA_4K_BLOCKBUSTER', 'Grand Cinema 4K Blockbuster Title Impact', 'titan-anim-type-stamp', '1.0s', 'master'],
    ['GOD_RAY_CREPUSCULAR_LIGHT', 'God-Ray Atmospheric Sunlight Breakthrough', 'titan-anim-bloom', '2.5s', 'master'],
    ['QUANTUM_SINGULARITY_FUSION', 'Quantum Fusion Core Ignition', 'titan-anim-plasma', '2.2s', 'master'],
    ['GOLDEN_HORIZON_CINEMA_PAN', 'Golden Horizon 70mm IMAX Cinema Pan', 'titan-anim-type-track', '3.0s', 'master'],
    ['CYBERNETIC_LASER_MATRIX_DSP', 'Cybernetic Laser Etch Matrix Processor', 'titan-anim-type-laser', '1.6s', 'master'],
    ['VR_360_SPHERICAL_PANORAMA', 'VR 360° Spherical Spatial Orbit', 'titan-anim-type-circular-orbit', '3.5s', 'master'],
    ['VOLUMETRIC_HOLOGRAM_3D', 'Volumetric True 3D Hologram Projection', 'titan-anim-hud-3d', '2.0s', 'master'],
    ['PARALLAX_CINEMA_DEEP_STAGE', 'Multi-Layer Depth Stage Parallax', 'titan-anim-float', '3.0s', 'master'],
    ['LIQUID_NEON_PLASMA_CORE', 'Liquid Neon Plasma Superheated Core', 'titan-anim-type-rainbow', '2.8s', 'master'],
    ['SUPERCHARGED_LIGHTNING_GRID', 'Supercharged Lightning Grid Array', 'titan-anim-type-zap', '0.9s', 'master'],
    ['INFINITE_FIBONACCI_SPIRAL', 'Infinite Fibonacci Golden Ratio Spiral', 'titan-anim-type-spiral-vortex', '3.0s', 'master'],
    ['DIMENSIONAL_RIFT_PORTAL', 'Dimensional Spacetime Rift Portal', 'titan-anim-vortex', '2.4s', 'master'],
    ['ULTIMATE_TITAN_GOD_TIER', '👑 Ultimate God-Tier Titan Master FX', 'titan-anim-type-rainbow', '2.0s', 'master']
];

textCategories.forEach((item, idx) => {
    defineTextAnim(idx, item[0], item[1], item[2], item[3], item[4]);
});

module.exports = {
    KINETIC_TEXT_256
};
