'use strict';

/**
 * 🐬 DANPHE FONTS 256 (0x00 to 0xFF)
 * Complete 256 Truly Unique, World-Class Typography Suite
 * 100% Non-Repeating: Seven-Segment, LCD, Dot-Matrix, Devanagari, Nepali, Cyberpunk, 
 * Cinematic, Luxury Serif, Swiss Sans, Brush Script, Monospace & 3D Retro.
 */

const CATEGORIES = {
    HARDWARE_LCD: 'Hardware & LCD Matrix',
    NEPALI_DEVANAGARI: 'Nepali & Devanagari',
    CYBERPUNK_SCI_FI: 'Cyberpunk & Sci-Fi',
    CINEMATIC_TITLE: 'Cinematic & Title Display',
    LUXURY_SERIF: 'Luxury & Editorial Serif',
    SWISS_SANS: 'Modern & Swiss Sans',
    BRUSH_SCRIPT: 'Handwritten & Brush Script',
    RETRO_MONO_3D: 'Monospace, Retro & 3D Art'
};

const rawFonts = [
    // ═════════════════════════════════════════════════════════════════════════
    // 📟 0x00 - 0x1F (0-31): HARDWARE, SEVEN-SEGMENT, LCD, DOT-MATRIX & CRT
    // ═════════════════════════════════════════════════════════════════════════
    { name: 'Seven Segment Red LED Digital', family: "'VT323', monospace, 'Courier New'", cat: CATEGORIES.HARDWARE_LCD, g: 'VT323', preview: '88:88:88 LED' },
    { name: 'Fourteen Segment Alphanumeric HUD', family: "'Share Tech Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Share+Tech+Mono', preview: 'ALPHANUMERIC 14-SEG' },
    { name: '16x16 Matrix LCD Green Terminal', family: "'Silkscreen', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Silkscreen:wght@700', preview: 'MATRIX LCD GREEN' },
    { name: '5x7 Dot Matrix Airport Flight Board', family: "'Share Tech Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Share+Tech+Mono', preview: 'DEPARTURES 10:45' },
    { name: 'VFD Vacuum Fluorescent Tube Display', family: "'Major Mono Display', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Major+Mono+Display', preview: 'VFD CYAN -24dB' },
    { name: 'Nixie Tube Glass Neon Filament', family: "'Monoton', cursive", cat: CATEGORIES.HARDWARE_LCD, g: 'Monoton', preview: 'NIXIE 1974' },
    { name: 'Casio Digital Watch LCD Chrono', family: "'VT323', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'VT323', preview: '12:00:00 ALARM' },
    { name: 'Split-Flap Train Departure Board', family: "'Oswald', sans-serif", cat: CATEGORIES.HARDWARE_LCD, g: 'Oswald:wght@700', preview: 'TRACK 04 EXPRESS' },
    { name: 'GameBoy 8-Bit Green Screen Pixel', family: "'Press Start 2P', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Press+Start+2P', preview: 'GAME BOY 1989' },
    { name: 'Commodore 64 PETSCII Character Set', family: "'Press Start 2P', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Press+Start+2P', preview: 'READY. LOAD "*",8,1' },
    { name: 'Atari 2600 Classic Arcade Raster', family: "'Silkscreen', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Silkscreen:wght@700', preview: 'HIGH SCORE 99990' },
    { name: 'ZX Spectrum 1982 TV Scanlines', family: "'Press Start 2P', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Press+Start+2P', preview: '10 PRINT "SPECTRUM"' },
    { name: 'IBM 3270 Mainframe Green Terminal', family: "'IBM Plex Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'IBM+Plex+Mono:wght@700', preview: 'CICS TRANSACTION ON' },
    { name: 'Teletext Ceefax 1970s Broadcast Grid', family: "'VT323', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'VT323', preview: 'P100 BBC CEEFAX' },
    { name: 'Amiga Topaz Bitmap Operating System', family: "'Share Tech Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Share+Tech+Mono', preview: 'Workbench 1.3 Amiga' },
    { name: 'DEC VT100 Amber Phosphor Glass', family: "'Space Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Space+Mono:wght@700', preview: 'VT100 ANSI TERMINAL' },
    { name: 'Barcode Code 39 Optical Scanner', family: "'Libre Barcode 39 Text', cursive, monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Libre+Barcode+39+Text', preview: '*TITAN-SCAN*' },
    { name: 'Electronic Shelf Label E-Ink Mono', family: "'Share Tech Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Share+Tech+Mono', preview: 'PRICE $24.99 USD' },
    { name: 'Audio Spectrum VUMeter Decibel Grid', family: "'JetBrains Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'JetBrains+Mono:wght@800', preview: '+3dB PEAK CLIP' },
    { name: 'Submarine Sonar Radar Display', family: "'Share Tech Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Share+Tech+Mono', preview: 'BEARING 045 SPEED 18' },
    { name: 'Oscilloscope Vector Lissajous Beam', family: "'Geo', sans-serif", cat: CATEGORIES.HARDWARE_LCD, g: 'Geo', preview: 'FREQ 440Hz SINE' },
    { name: 'Morse Telegraph Pulse Matrix', family: "'Courier Prime', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Courier+Prime:wght@700', preview: '... --- ... SOS' },
    { name: 'NASA Apollo Guidance Computer DSKY', family: "'Share Tech Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Share+Tech+Mono', preview: 'VERB 37 NOUN 63' },
    { name: 'Seiko Digital Chronograph Matrix', family: "'Silkscreen', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Silkscreen', preview: 'LAP 01:24:88' },
    { name: 'Treadmill Fitness LED Console', family: "'VT323', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'VT323', preview: 'SPEED 12.5 KM/H' },
    { name: 'Microwave Oven 7-Segment Green Timer', family: "'VT323', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'VT323', preview: 'COOK TIME 02:30' },
    { name: 'Gas Station Fuel Pump Digital Gauge', family: "'Share Tech Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Share+Tech+Mono', preview: 'OCTANE 95 $4.20' },
    { name: 'Taxi Fare Meter LED Red Rate', family: "'VT323', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'VT323', preview: 'FARE $14.50 EX' },
    { name: 'Subway Destination Orange LED Sign', family: "'Silkscreen', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Silkscreen:wght@700', preview: 'EXP TO AIRPORT' },
    { name: 'Hospital Heart Rate ECG Monitor Vitals', family: "'JetBrains Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'JetBrains+Mono:wght@700', preview: 'BPM 72 SPO2 99%' },
    { name: 'CNC Milling Machine Coordinate HUD', family: "'Space Mono', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'Space+Mono:wght@700', preview: 'X+124.05 Y-88.32' },
    { name: 'Multimeter Digital Voltage Probe', family: "'VT323', monospace", cat: CATEGORIES.HARDWARE_LCD, g: 'VT323', preview: '240.5 V AC 50Hz' },

    // ═════════════════════════════════════════════════════════════════════════
    // 🇳🇵 0x20 - 0x3F (32-63): NEPALI, DEVANAGARI & SOUTH ASIAN TYPOGRAPHY
    // ═════════════════════════════════════════════════════════════════════════
    { name: 'Sagarmatha Display Heritage', family: "'Yatra One', cursive", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Yatra+One', preview: 'सगरमाथा सौन्दर्य' },
    { name: 'Kantipur Bold Editorial', family: "'Rozha One', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Rozha+One', preview: 'कान्तिपुर दैनिक' },
    { name: 'Mukti Sans High Legibility', family: "'Mukta', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Mukta:wght@700;800', preview: 'मुक्ति देवनागरी' },
    { name: 'Danphe Poppins Nepali Modern', family: "'Poppins', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Poppins:wght@700;900', preview: 'डाँफे सिनेमा' },
    { name: 'Gotu Classical Sanskrit Calligraphy', family: "'Gotu', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Gotu', preview: 'गोतु शास्त्रीय' },
    { name: 'Teko Himalayan Heavy Headline', family: "'Teko', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Teko:wght@700', preview: 'हिमालय विशाल' },
    { name: 'Martel Monumental Royal Inscription', family: "'Martel', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Martel:wght@900', preview: 'मार्तेल राजदरबार' },
    { name: 'Eczar Majestic Editorial Serif', family: "'Eczar', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Eczar:wght@800', preview: 'एक्जार साहित्य' },
    { name: 'Rajdhani Tactical Kathmandu Sans', family: "'Rajdhani', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Rajdhani:wght@700', preview: 'राजधानी काठमाडौं' },
    { name: 'Kalam Authentic Handcraft Script', family: "'Kalam', cursive", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Kalam:wght@700', preview: 'कलम हस्तलिखित' },
    { name: 'Changa One Annapurna Giant', family: "'Changa One', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Changa+One', preview: 'अन्नपूर्ण टाकुरा' },
    { name: 'Karma Ancient Vedic Stone Inscription', family: "'Karma', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Karma:wght@700', preview: 'कर्म शिलापत्र' },
    { name: 'Federo Newari Architectural Display', family: "'Federo', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Federo', preview: 'काष्ठमण्डप कला' },
    { name: 'Cinzel Decorative Patan Durbar', family: "'Cinzel Decorative', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Cinzel+Decorative:wght@700', preview: 'पाटन दरबार' },
    { name: 'Bowlby One Everest Ultra Heavy', family: "'Bowlby One SC', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Bowlby+One+SC', preview: 'एभरेस्ट शिखर' },
    { name: 'Saira Condensed Chitwan Safari', family: "'Saira Condensed', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Saira+Condensed:wght@800', preview: 'चितवन राष्ट्रिय' },
    { name: 'Modak Puffed Candy Devanagari', family: "'Modak', cursive", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Modak', preview: 'मोदक मिठास' },
    { name: 'Amita Folk Dancing Calligraphy', family: "'Amita', cursive", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Amita:wght@700', preview: 'अमिता लोकनृत्य' },
    { name: 'Sahitya Sanskrit Philosophical', family: "'Sahitya', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Sahitya:wght@700', preview: 'साहित्य दर्शन' },
    { name: 'Kurale Eastern Heritage Folk', family: "'Kurale', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Kurale', preview: 'कुराले परम्परा' },
    { name: 'Arya High-Contrast Monumental', family: "'Arya', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Arya:wght@700', preview: 'आर्य संस्कृति' },
    { name: 'Palanquin Dark Royal Procession', family: "'Palanquin Dark', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Palanquin+Dark:wght@700', preview: 'पालकी शोभायात्रा' },
    { name: 'Laila Decorative Sacred Lotus', family: "'Laila', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Laila:wght@700', preview: 'लैला कमल' },
    { name: 'Jaldi Ultra-Clean Highway Sign', family: "'Jaldi', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Jaldi:wght@700', preview: 'जल्दी राजमार्ग' },
    { name: 'Biryani Extra Bold Feast', family: "'Biryani', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Biryani:wght@800', preview: 'बिरयानी उत्सव' },
    { name: 'Sarala Modernist Clean Grotesk', family: "'Sarala', sans-serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Sarala:wght@700', preview: 'सरला आधुनिक' },
    { name: 'Ranga Street Wall Spray Brush', family: "'Ranga', cursive", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Ranga:wght@700', preview: 'रङ्ग चित्रकला' },
    { name: 'Tillana Classical Temple Dancer', family: "'Tillana', cursive", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Tillana:wght@800', preview: 'तिल्लाना नृत्य' },
    { name: 'Vesper Libre Ancient Manuscript', family: "'Vesper Libre', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Vesper+Libre:wght@700', preview: 'ग्रन्थ पाण्डुलिपि' },
    { name: 'Halant Crisp Devanagari Geometry', family: "'Halant', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Halant:wght@700', preview: 'हलन्त व्याकरण' },
    { name: 'Glegoo Modern Devanagari Slab', family: "'Glegoo', serif", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Glegoo:wght@700', preview: 'ग्लिगु देवनागरी' },
    { name: 'Dekko Friendly Handwriting Chalk', family: "'Dekko', cursive", cat: CATEGORIES.NEPALI_DEVANAGARI, g: 'Dekko', preview: 'डेक्को अक्षर' },

    // ═════════════════════════════════════════════════════════════════════════
    // ⚡ 0x40 - 0x5F (64-95): CYBERPUNK, SCI-FI, NEON & MECHA TITANIUM
    // ═════════════════════════════════════════════════════════════════════════
    { name: 'Orbitron Cyber Matrix 2077', family: "'Orbitron', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Orbitron:wght@900', preview: 'ORBITRON 2077' },
    { name: 'Audiowide Synthwave Outrun', family: "'Audiowide', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Audiowide', preview: 'SYNTHWAVE 84' },
    { name: 'Monoton Triple Strip Neon', family: "'Monoton', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Monoton', preview: 'NEON TOKYO' },
    { name: 'Syncopate Hyperwide Hologram', family: "'Syncopate', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Syncopate:wght@700', preview: 'SYNCOPATE HUD' },
    { name: 'Michroma Tachyon Warp Drive', family: "'Michroma', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Michroma', preview: 'WARP FACTOR 9' },
    { name: 'Chakra Petch Tactical Armor', family: "'Chakra Petch', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Chakra+Petch:wght@700', preview: 'TACTICAL UNIT' },
    { name: 'Oxanium Cybernetic Exoskeleton', family: "'Oxanium', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Oxanium:wght@800', preview: 'EXOSKELETON V4' },
    { name: 'Bruno Ace SC Aerospace Fighter', family: "'Bruno Ace SC', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Bruno+Ace+SC', preview: 'AEROSPACE JET' },
    { name: 'Saira Stencil SpecOps Military', family: "'Saira Stencil One', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Saira+Stencil+One', preview: 'SECTOR-7 SECURE' },
    { name: 'Wallpoet Reinforced Bunker Stencil', family: "'Wallpoet', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Wallpoet', preview: 'BUNKER ACCESS' },
    { name: 'Major Mono Display Quantum Glitch', family: "'Major Mono Display', monospace", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Major+Mono+Display', preview: 'QUANTUM GLITCH' },
    { name: 'Plaster Heavy Brutalist Concrete', family: "'Plaster', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Plaster', preview: 'BRUTAL BLOCK' },
    { name: 'Black Ops One Heavy Tank Division', family: "'Black Ops One', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Black+Ops+One', preview: 'HEAVY ARMOR' },
    { name: 'Goldman Cybernetic Defense Grid', family: "'Goldman', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Goldman:wght@700', preview: 'DEFENSE GRID' },
    { name: 'Nova Square Holographic Scanner', family: "'Nova Square', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Nova+Square', preview: 'SCAN MATRIX' },
    { name: 'Geo Deep Space Telemetry Terminal', family: "'Geo', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Geo', preview: 'DEEP SPACE SAT' },
    { name: 'Megrim Wireframe Laser Grid', family: "'Megrim', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Megrim', preview: 'LASER VECTOR' },
    { name: 'Faster One Nitro Turbocharged', family: "'Faster One', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Faster+One', preview: 'NITRO BOOST' },
    { name: 'Nico Moji Akihabara Neo Cyber', family: "'Orbitron', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Orbitron:wght@800', preview: 'NEO AKIHABARA' },
    { name: 'Electrolize Nanotech Circuit', family: "'Electrolize', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Electrolize', preview: 'NANO CIRCUIT' },
    { name: 'Zen Dots Futuristic Matrix', family: "'Zen Dots', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Zen+Dots', preview: 'ZEN MATRIX' },
    { name: 'Koulen Brutal Cyber Construction', family: "'Koulen', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Koulen', preview: 'HEAVY IMPACT' },
    { name: 'Tourney Wireframe Cyber Sports', family: "'Tourney', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Tourney:wght@900', preview: 'CYBER LEAGUE' },
    { name: 'Iceland Cryogenic Frost Vault', family: "'Iceland', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Iceland', preview: 'CRYO ZERO -273C' },
    { name: 'Turret Road Heavy Excavator', family: "'Turret Road', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Turret+Road:wght@800', preview: 'HEAVY MECH' },
    { name: 'Geostar Starlight Astrogation', family: "'Geostar', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Geostar', preview: 'ASTRO NAV 09' },
    { name: 'Iceberg Glacial Crystalline Ice', family: "'Iceberg', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Iceberg', preview: 'CRYSTAL POLAR' },
    { name: 'Ropa Sans Cockpit Instrument', family: "'Ropa Sans', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Ropa+Sans', preview: 'COCKPIT HUD' },
    { name: 'Quantico Fighter Jet Crosshair', family: "'Quantico', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Quantico:wght@700', preview: 'TARGET LOCKED' },
    { name: 'Allerta Stencil Nuclear Hazard', family: "'Allerta Stencil', sans-serif", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Allerta+Stencil', preview: 'HAZARD ZONE' },
    { name: 'Nova Oval Orbital Satellite Arc', family: "'Nova Oval', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Nova+Oval', preview: 'ORBIT 400KM' },
    { name: 'Nova Round Space Station Node', family: "'Nova Round', cursive", cat: CATEGORIES.CYBERPUNK_SCI_FI, g: 'Nova+Round', preview: 'STATION NODE' },

    // ═════════════════════════════════════════════════════════════════════════
    // 🎬 0x60 - 0x7F (96-127): CINEMATIC, BLOCKBUSTER & TRAILER TITLES
    // ═════════════════════════════════════════════════════════════════════════
    { name: 'Bebas Neue Cinema Blockbuster', family: "'Bebas Neue', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Bebas+Neue', preview: 'THE BLOCKBUSTER' },
    { name: 'Oswald High-Impact Action Movie', family: "'Oswald', sans-serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Oswald:wght@700', preview: 'MAXIMUM OVERDRIVE' },
    { name: 'Anton Mammoth Cinema Monolith', family: "'Anton', sans-serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Anton', preview: 'MONOLITH TITAN' },
    { name: 'Russo One Red October Epic', family: "'Russo One', sans-serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Russo+One', preview: 'RED OCTOBER' },
    { name: 'Righteous 1980s Retro Action Reel', family: "'Righteous', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Righteous', preview: 'MIAMI VICE 1984' },
    { name: 'Black Han Sans Ultra Heavy Slab', family: "'Black Han Sans', sans-serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Black+Han+Sans', preview: 'HEAVY TITAN' },
    { name: 'Titan One 3D Extruded Animation', family: "'Titan One', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Titan+One', preview: '3D ANIMATION' },
    { name: 'Fugaz One Kinetic Fast Zoom', family: "'Fugaz One', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Fugaz+One', preview: 'FAST & FURIOUS' },
    { name: 'Secular One Hollywood Billboard', family: "'Secular One', sans-serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Secular+One', preview: 'WORLD PREMIERE' },
    { name: 'Passion One Heavy Punch Title', family: "'Passion One', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Passion+One:wght@900', preview: 'KNOCKOUT PUNCH' },
    { name: 'Alfa Slab One 1890s Woodblock Poster', family: "'Alfa Slab One', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Alfa+Slab+One', preview: 'WANTED POSTER' },
    { name: 'Ultra Monster Heavyweight Serif', family: "'Ultra', serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Ultra', preview: 'MONSTER TRUCK' },
    { name: 'Bungee Inline Marquee Cinema Sign', family: "'Bungee Inline', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Bungee+Inline', preview: 'BROADWAY LIGHTS' },
    { name: 'Kanit Aggressive Condensed Thai Bold', family: "'Kanit', sans-serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Kanit:wght@900', preview: 'EXTREME POWER' },
    { name: 'Squada One High Velocity Racing', family: "'Squada One', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Squada+One', preview: 'VELOCITY RACER' },
    { name: 'League Gothic 1930s Film Noir', family: "'League Gothic', sans-serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'League+Gothic', preview: 'MIDNIGHT NOIR' },
    { name: 'Staatliches Bauhaus Propaganda', family: "'Staatliches', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Staatliches', preview: 'BAUHAUS 1919' },
    { name: 'Rowdies Heavy Street Poster', family: "'Rowdies', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Rowdies:wght@700', preview: 'STREET FIGHT' },
    { name: 'Carter One Casual Hollywood Title', family: "'Carter One', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Carter+One', preview: 'SUMMER CARTOON' },
    { name: 'Fredoka Rounded 3D Bubble Title', family: "'Fredoka', sans-serif", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Fredoka:wght@700', preview: 'BUBBLE POP' },
    { name: 'Lilita One Chunky Pop Display', family: "'Lilita One', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Lilita+One', preview: 'CHUNKY MONKEY' },
    { name: 'Shrikhand Handpainted Cinema Signboard', family: "'Shrikhand', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Shrikhand', preview: 'HAND PAINTED' },
    { name: 'Chango Ancient Incan Monument', family: "'Chango', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Chango', preview: 'INCAN GOLD' },
    { name: 'Rammetto One Ultra Pop Shadow', family: "'Rammetto One', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Rammetto+One', preview: 'RETRO CANDY' },
    { name: 'Bungee Shade 3D Perspective Block', family: "'Bungee Shade', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Bungee+Shade', preview: '3D PERSPECTIVE' },
    { name: 'Creepster Midnight Horror Monster', family: "'Creepster', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Creepster', preview: 'NIGHTMARE FX' },
    { name: 'Nosifer Dripping Blood Creature', family: "'Nosifer', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Nosifer', preview: 'BLOOD DRIP' },
    { name: 'Eater Haunted Graveyard Grunge', family: "'Eater', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Eater', preview: 'GRAVEYARD' },
    { name: 'Shojumaru Samurai Epic Brush Title', family: "'Shojumaru', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Shojumaru', preview: 'SAMURAI SWORD' },
    { name: 'Frijole Heavy Grunge Punk Rock', family: "'Frijole', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Frijole', preview: 'PUNK ROCK' },
    { name: 'Sancreek Wild West Saloon Woodtype', family: "'Sancreek', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Sancreek', preview: 'WILD WEST' },
    { name: 'Smokum Western Cowboy Outlaw', family: "'Smokum', cursive", cat: CATEGORIES.CINEMATIC_TITLE, g: 'Smokum', preview: 'OUTLAW BANDIT' },

    // ═════════════════════════════════════════════════════════════════════════
    // 📰 0x80 - 0x9F (128-159): LUXURY, EDITORIAL & FASHION SERIF
    // ═════════════════════════════════════════════════════════════════════════
    { name: 'Playfair Display Vogue Cover', family: "'Playfair Display', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Playfair+Display:wght@900', preview: 'HAUTE COUTURE' },
    { name: 'Cinzel Royal Imperial Monument', family: "'Cinzel', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Cinzel:wght@900', preview: 'IMPERIAL ROME' },
    { name: 'Cormorant Garamond French Elegance', family: "'Cormorant Garamond', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Cormorant+Garamond:wght@700', preview: 'CHÂTEAU DE PARIS' },
    { name: 'Bodoni Moda Milanese Runway Fashion', family: "'Bodoni Moda', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Bodoni+Moda:ital,wght@1,900', preview: 'MILANO RUNWAY' },
    { name: 'Prata Italian Renaissance Luxury', family: "'Prata', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Prata', preview: 'FIRENZE ARTE' },
    { name: 'DM Serif Display Regal Headline', family: "'DM Serif Display', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'DM+Serif+Display', preview: 'ROYAL DYNASTY' },
    { name: 'Marcellus Classical Roman Column', family: "'Marcellus', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Marcellus', preview: 'COLOSSEUM' },
    { name: 'Abril Fatface Dramatic French Magazine', family: "'Abril Fatface', cursive", cat: CATEGORIES.LUXURY_SERIF, g: 'Abril+Fatface', preview: 'VOGUE PARIS' },
    { name: 'Castoro Titling Oxford Heritage', family: "'Castoro Titling', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Castoro+Titling', preview: 'OXFORD MANOR' },
    { name: 'Yeseva One Velvet Empress Serif', family: "'Yeseva One', cursive", cat: CATEGORIES.LUXURY_SERIF, g: 'Yeseva+One', preview: 'EMPRESS SILK' },
    { name: 'Fraunces Optical Variable Black', family: "'Fraunces', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Fraunces:opsz,wght@144,900', preview: 'EDITORIAL BLACK' },
    { name: 'Bellefair Diamond High Jewelry', family: "'Bellefair', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Bellefair', preview: 'TIFFANY & CO.' },
    { name: 'Italiana Via Condotti Fashion', family: "'Italiana', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Italiana', preview: 'VIA CONDOTTI' },
    { name: 'Caudex Illuminated Bible Manuscript', family: "'Caudex', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Caudex:wght@700', preview: 'CODEX VATICAN' },
    { name: 'Unna Scandinavian Minimalist Serif', family: "'Unna', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Unna:wght@700', preview: 'NORDIC DESIGN' },
    { name: 'Vidaloka Parisian Perfume Bottle', family: "'Vidaloka', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Vidaloka', preview: 'PARFUM DE LUXE' },
    { name: 'Oranienbaum St. Petersburg Palace', family: "'Oranienbaum', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Oranienbaum', preview: 'WINTER PALACE' },
    { name: 'Forum Ancient Forum Trajan Column', family: "'Forum', cursive", cat: CATEGORIES.LUXURY_SERIF, g: 'Forum', preview: 'FORUM ROMANUM' },
    { name: 'GFS Didot Greek Classic Philosophy', family: "'GFS Didot', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'GFS+Didot', preview: 'ATHENS PHILOSOPHY' },
    { name: 'Spectral Oxford University Press', family: "'Spectral', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Spectral:wght@800', preview: 'ENCYCLOPEDIA' },
    { name: 'Faustina Royal Inscription Serif', family: "'Faustina', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Faustina:wght@800', preview: 'SOVEREIGN' },
    { name: 'El Messiri Royal Alexandria Serif', family: "'El Messiri', sans-serif", cat: CATEGORIES.LUXURY_SERIF, g: 'El+Messiri:wght@700', preview: 'ALEXANDRIA' },
    { name: 'BioRhyme Ultra Expanded Slab Serif', family: "'BioRhyme', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'BioRhyme:wght@800', preview: 'EXPANDED SLAB' },
    { name: 'Cormorant Unicase Modern Avant-Garde', family: "'Cormorant Unicase', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Cormorant+Unicase:wght@700', preview: 'UNICASE MODERNE' },
    { name: 'Arapey Soft Cashmere Editorial', family: "'Arapey', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Arapey', preview: 'CASHMERE SILK' },
    { name: 'Cardo Cambridge Scholar Archive', family: "'Cardo', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Cardo:wght@700', preview: 'ARCHIVE 1584' },
    { name: 'Suranna Royal Maharajah Court', family: "'Suranna', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Suranna', preview: 'ROYAL COURT' },
    { name: 'Trirong Grand Bangkok Palace', family: "'Trirong', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Trirong:wght@700', preview: 'GRAND PALACE' },
    { name: 'Pridi Siamese Royal Inscription', family: "'Pridi', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Pridi:wght@700', preview: 'SIAM HERITAGE' },
    { name: 'Bentham British Heritage Country', family: "'Bentham', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Bentham', preview: 'ESTATE 1840' },
    { name: 'Old Standard TT Victorian Newspaper', family: "'Old Standard TT', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Old+Standard+TT:wght@700', preview: 'THE TIMES 1890' },
    { name: 'Baskervville English Classical Type', family: "'Baskervville', serif", cat: CATEGORIES.LUXURY_SERIF, g: 'Baskervville', preview: 'BASKERVILLE' },

    // ═════════════════════════════════════════════════════════════════════════
    // 💎 0xA0 - 0xBF (160-191): MODERN SANS-SERIF & SWISS GROTESK
    // ═════════════════════════════════════════════════════════════════════════
    { name: 'Inter Display Pro Silicon Valley', family: "'Inter', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Inter:wght@900', preview: 'INTER DISPLAY' },
    { name: 'Montserrat Bauhaus Architecture', family: "'Montserrat', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Montserrat:wght@900', preview: 'MONTSERRAT BLACK' },
    { name: 'Plus Jakarta Sans Fintech Pro', family: "'Plus Jakarta Sans', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Plus+Jakarta+Sans:wght@800', preview: 'PLUS JAKARTA' },
    { name: 'Outfit Ultra Geometric Tech', family: "'Outfit', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Outfit:wght@900', preview: 'OUTFIT GEOMETRIC' },
    { name: 'Sora Precision Aerospace UI', family: "'Sora', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Sora:wght@800', preview: 'SORA PRECISION' },
    { name: 'Urbanist Contemporary Architectural', family: "'Urbanist', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Urbanist:wght@900', preview: 'URBANIST 900' },
    { name: 'Manrope Minimalist Design System', family: "'Manrope', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Manrope:wght@800', preview: 'MANROPE STUDIO' },
    { name: 'Work Sans Clean Swiss Typography', family: "'Work Sans', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Work+Sans:wght@900', preview: 'WORK SANS SWISS' },
    { name: 'Syne Avant-Garde Radical Display', family: "'Syne', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Syne:wght@800', preview: 'SYNE RADICAL' },
    { name: 'Epilogue Heavy Industrial Grotesk', family: "'Epilogue', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Epilogue:wght@900', preview: 'EPILOGUE HEAVY' },
    { name: 'DM Sans High-Definition Clear', family: "'DM Sans', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'DM+Sans:wght@900', preview: 'DM SANS HD' },
    { name: 'Lexend Deca Cognitive Legibility', family: "'Lexend Deca', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Lexend+Deca:wght@800', preview: 'LEXEND DECA' },
    { name: 'Red Hat Display Enterprise Core', family: "'Red Hat Display', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Red+Hat+Display:wght@900', preview: 'RED HAT ENTERPRISE' },
    { name: 'Space Grotesk Brutalist Tech', family: "'Space Grotesk', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Space+Grotesk:wght@700', preview: 'SPACE GROTESK' },
    { name: 'Albert Sans Dynamic UI Geometric', family: "'Albert Sans', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Albert+Sans:wght@900', preview: 'ALBERT SANS' },
    { name: 'Instrument Sans Minimal Art Tool', family: "'Instrument Sans', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Instrument+Sans:wght@700', preview: 'INSTRUMENT UI' },
    { name: 'Hanken Grotesk Nordic Clean', family: "'Hanken Grotesk', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Hanken+Grotesk:wght@900', preview: 'HANKEN GROTESK' },
    { name: 'Figtree Crisp Modern Geometric', family: "'Figtree', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Figtree:wght@900', preview: 'FIGTREE CRISP' },
    { name: 'Geist Sans High Performance Dev', family: "'Inter', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Inter:wght@800', preview: 'GEIST SANS VERCEL' },
    { name: 'Gabarito Playful Modern Display', family: "'Gabarito', cursive", cat: CATEGORIES.SWISS_SANS, g: 'Gabarito:wght@900', preview: 'GABARITO PLAY' },
    { name: 'Onest Universal Multilingual Sans', family: "'Onest', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Onest:wght@800', preview: 'ONEST GLOBAL' },
    { name: 'Spline Sans High Precision Vector', family: "'Spline Sans', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Spline+Sans:wght@700', preview: 'SPLINE 3D SANS' },
    { name: 'Schibsted Grotesk Scandinavian Press', family: "'Schibsted Grotesk', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Schibsted+Grotesk:wght@900', preview: 'SCHIBSTED PRESS' },
    { name: 'Public Sans Official Government Clear', family: "'Public Sans', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Public+Sans:wght@900', preview: 'PUBLIC SANS' },
    { name: 'Chivo Black Heavyweight Headline', family: "'Chivo', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Chivo:wght@900', preview: 'CHIVO HEADLINE' },
    { name: 'Darker Grotesque Deep Noir Sans', family: "'Darker Grotesque', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Darker+Grotesque:wght@900', preview: 'DARKER GROTESQUE' },
    { name: 'Golos Text Contemporary Multilingual', family: "'Golos Text', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Golos+Text:wght@800', preview: 'GOLOS TEXT' },
    { name: 'Unbounded Ultra Expanded Display', family: "'Unbounded', cursive", cat: CATEGORIES.SWISS_SANS, g: 'Unbounded:wght@900', preview: 'UNBOUNDED EXP' },
    { name: 'Overpass High Contrast Highway', family: "'Overpass', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Overpass:wght@900', preview: 'OVERPASS SPEED' },
    { name: 'Archivo Black Monumental Poster', family: "'Archivo Black', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Archivo+Black', preview: 'ARCHIVO BLACK' },
    { name: 'Prompt Heavy Thai Futuristic', family: "'Prompt', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Prompt:wght@800', preview: 'PROMPT FUTURA' },
    { name: 'Krona One Swedish Navigational', family: "'Krona One', sans-serif", cat: CATEGORIES.SWISS_SANS, g: 'Krona+One', preview: 'KRONA SWEDEN' },

    // ═════════════════════════════════════════════════════════════════════════
    // 🖋️ 0xC0 - 0xDF (192-223): HANDWRITTEN, BRUSH SCRIPT & CALLIGRAPHY
    // ═════════════════════════════════════════════════════════════════════════
    { name: 'Dancing Script Dynamic Bounce', family: "'Dancing Script', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Dancing+Script:wght@700', preview: 'Dancing In The Rain' },
    { name: 'Pacifico Hawaiian Surfboard Script', family: "'Pacifico', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Pacifico', preview: 'Pacific Beach Surf' },
    { name: 'Great Vibes Royal Ballroom Script', family: "'Great Vibes', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Great+Vibes', preview: 'Royal Wedding Gala' },
    { name: 'Caveat Casual Daily Marker Pen', family: "'Caveat', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Caveat:wght@700', preview: 'Quick handwritten note' },
    { name: 'Satisfy Smooth Velvet Brush', family: "'Satisfy', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Satisfy', preview: 'Smooth Velvet Coffee' },
    { name: 'Kaushan Script Street Mural Brush', family: "'Kaushan Script', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Kaushan+Script', preview: 'Street Art Graffiti' },
    { name: 'Alex Brush Ribbon Copperplate', family: "'Alex Brush', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Alex+Brush', preview: 'Signature Excellence' },
    { name: 'Sacramento Delicate Monoline Wire', family: "'Sacramento', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Sacramento', preview: 'Delicate Wire Art' },
    { name: 'Allura Platinum Swirl Flourish', family: "'Allura', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Allura', preview: 'Golden Elegance' },
    { name: 'Parisienne French Romance Script', family: "'Parisienne', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Parisienne', preview: 'Bonjour Mon Amour' },
    { name: 'Yellowtail 1950s Diner Neon Script', family: "'Yellowtail', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Yellowtail', preview: 'Diner Burger 50s' },
    { name: 'Permanent Marker Heavy Black Ink', family: "'Permanent Marker', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Permanent+Marker', preview: 'PERMANENT INK' },
    { name: 'Rock Salt Urban Chalkboard Grunge', family: "'Rock Salt', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Rock+Salt', preview: 'CHALK ON WALL' },
    { name: 'Covered By Your Grace Personal Diary', family: "'Covered By Your Grace', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Covered+By+Your+Grace', preview: 'Dear Secret Diary' },
    { name: 'Shadows Into Light Intimate Ballpoint', family: "'Shadows Into Light', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Shadows+Into+Light', preview: 'Memories Fade Slow' },
    { name: 'Bad Script Quick Note Spontaneous', family: "'Bad Script', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Bad+Script', preview: 'Meeting At Five' },
    { name: 'Homemade Apple Grandmother Recipe', family: "'Homemade Apple', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Homemade+Apple', preview: 'Apple Pie Recipe' },
    { name: 'Marck Script Cyrillic Ribbon Flow', family: "'Marck Script', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Marck+Script', preview: 'Poetry In Motion' },
    { name: 'Courgette French Café Chalkboard', family: "'Courgette', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Courgette', preview: 'Café De Flore Menu' },
    { name: 'Damion Casual 1960s Speed Script', family: "'Damion', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Damion', preview: 'Speedway Racer' },
    { name: 'La Belle Aurore Tender Love Letter', family: "'La Belle Aurore', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'La+Belle+Aurore', preview: 'Yours Forever Darling' },
    { name: 'Gloria Hallelujah Comic Scribble', family: "'Gloria Hallelujah', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Gloria+Hallelujah', preview: 'Comic Book POW!' },
    { name: 'Gochi Hand Japanese Felt Tip Marker', family: "'Gochi Hand', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Gochi+Hand', preview: 'Anime Sketch Note' },
    { name: 'Kavivanar Organic Tamil Bamboo Pen', family: "'Kavivanar', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Kavivanar', preview: 'Bamboo Quill Art' },
    { name: 'Loved by the King Royal Decree Pen', family: "'Loved by the King', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Loved+by+the+King', preview: 'Royal Decree 1642' },
    { name: 'Meddon 18th Century Law Quill', family: "'Meddon', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Meddon', preview: 'Magna Carta Oath' },
    { name: 'Mr De Havilland Aristocrat Signature', family: "'Mr De Havilland', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Mr+De+Havilland', preview: 'Lord Harrington' },
    { name: 'Reenie Beanie Doodled Sketchpad', family: "'Reenie Beanie', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Reenie+Beanie', preview: 'Coffee Shop Napkin' },
    { name: 'Ruthie Ultra Elegant Wedding Flourish', family: "'Ruthie', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Ruthie', preview: 'Cordially Invited' },
    { name: 'Sue Ellen Francisco San Francisco Pen', family: "'Sue Ellen Francisco', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Sue+Ellen+Francisco', preview: 'Golden Gate Fog' },
    { name: 'Zeyada Spontaneous Freehand Felt', family: "'Zeyada', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Zeyada', preview: 'Art Studio Draft' },
    { name: 'Cedarville Cursive Vintage Classroom', family: "'Cedarville Cursive', cursive", cat: CATEGORIES.BRUSH_SCRIPT, g: 'Cedarville+Cursive', preview: 'Cursive Writing 101' },

    // ═════════════════════════════════════════════════════════════════════════
    // 💻 0xE0 - 0xFF (224-255): TERMINAL, MONOSPACE, RETRO 80S & 3D ART
    // ═════════════════════════════════════════════════════════════════════════
    { name: 'JetBrains Mono Cinema HUD Terminal', family: "'JetBrains Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'JetBrains+Mono:wght@800', preview: 'const titan = true;' },
    { name: 'Fira Code Ligature Developer Pro', family: "'Fira Code', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Fira+Code:wght@700', preview: 'if (fps === 120) => ok' },
    { name: 'Space Mono Deep Space Telemetry', family: "'Space Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Space+Mono:wght@700', preview: 'SAT_ID: TITAN_01' },
    { name: 'VT323 Retro CRT Phosphor Green', family: "'VT323', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'VT323', preview: 'BOOTING DANPHE OS...' },
    { name: 'Share Tech Mono Tactical Drone HUD', family: "'Share Tech Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Share+Tech+Mono', preview: 'DRONE ALT: 450M' },
    { name: 'Cutive Mono 1920s UnderWood Typewriter', family: "'Cutive Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Cutive+Mono', preview: 'CHAPTER ONE: RAIN' },
    { name: 'IBM Plex Mono Enterprise Terminal', family: "'IBM Plex Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'IBM+Plex+Mono:wght@700', preview: 'SYSTEM/370 ONLINE' },
    { name: 'Silkscreen 8-Bit GameBoy Arcade', family: "'Silkscreen', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Silkscreen:wght@700', preview: 'STAGE 1 COMPLETED' },
    { name: 'Press Start 2P NES 8-Bit Nintendo', family: "'Press Start 2P', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Press+Start+2P', preview: 'PRESS START BUTTON' },
    { name: 'Rubik Glitch Corrupted Data Feed', family: "'Rubik Glitch', system-ui", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Glitch', preview: 'SYSTEM ERROR 0xFA' },
    { name: 'Syne Mono Experimental Cyber Terminal', family: "'Syne Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Syne+Mono', preview: 'AVANT GARDE CODE' },
    { name: 'DM Mono High Precision Console', family: "'DM Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'DM+Mono:wght@500', preview: 'KERNEL COMPILED' },
    { name: 'Azeret Mono Cyber Defense Bureau', family: "'Azeret Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Azeret+Mono:wght@900', preview: 'FIREWALL ACTIVE' },
    { name: 'Spline Sans Mono 3D Vector Grid', family: "'Spline Sans Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Spline+Sans+Mono:wght@700', preview: 'VERTEX [12, 84, 90]' },
    { name: 'Red Hat Mono Modern Linux Core', family: "'Red Hat Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Red+Hat+Mono:wght@700', preview: 'root@titan-server:~#' },
    { name: 'Overpass Mono Aerospace Beacon', family: "'Overpass Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Overpass+Mono:wght@700', preview: 'RADAR BEACON 109.5' },
    { name: 'Nova Mono Geometric Matrix Grid', family: "'Nova Mono', monospace", cat: CATEGORIES.RETRO_MONO_3D, g: 'Nova+Mono', preview: 'MATRIX 10101001' },
    { name: 'Fascinate Disco 1970s Neon Bulb', family: "'Fascinate', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Fascinate', preview: 'DISCO FEVER 1977' },
    { name: 'Rye Wild West Saloon Wooden Sign', family: "'Rye', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rye', preview: 'SALOON & HOTEL' },
    { name: 'Vast Shadow Vintage 3D Drop Cast', family: "'Vast Shadow', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Vast+Shadow', preview: '3D VINTAGE DROP' },
    { name: 'Bungee Outline Open Neon Tube', family: "'Bungee Outline', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Bungee+Outline', preview: 'OPEN ALL NIGHT' },
    { name: 'Londrina Shadow 3D Pop Poster', family: "'Londrina Shadow', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Londrina+Shadow', preview: 'POP ART POSTER' },
    { name: 'Monofett Ultra Thin Wire Matrix', family: "'Monofett', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Monofett', preview: 'WIRE MATRIX ART' },
    { name: 'Rubik Vinyl 1970s Disco Record Album', family: "'Rubik Vinyl', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Vinyl', preview: 'VINYL RECORD 33RPM' },
    { name: 'Rubik Wet Paint Fresh Street Drip', family: "'Rubik Wet Paint', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Wet+Paint', preview: 'WET PAINT SPRAY' },
    { name: 'Rubik 80s Fade Synthwave Sunset', family: "'Rubik 80s Fade', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+80s+Fade', preview: 'SYNTHWAVE SUNSET' },
    { name: 'Rubik Beastly Monster Fur Title', family: "'Rubik Beastly', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Beastly', preview: 'BEAST MONSTER' },
    { name: 'Rubik Burned Scorched Flame Fire', family: "'Rubik Burned', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Burned', preview: 'SCORCHED FLAME' },
    { name: 'Rubik Distressed Industrial Grunge', family: "'Rubik Distressed', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Distressed', preview: 'INDUSTRIAL GRUNGE' },
    { name: 'Rubik Gemstones Crystalline Jewel', family: "'Rubik Gemstones', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Gemstones', preview: 'DIAMOND GEMSTONE' },
    { name: 'Rubik Puddles Water Splash Wave', family: "'Rubik Puddles', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Puddles', preview: 'WATER SPLASH' },
    { name: 'Rubik Storm Hurricane Lightning', family: "'Rubik Storm', cursive", cat: CATEGORIES.RETRO_MONO_3D, g: 'Rubik+Storm', preview: 'STORM LIGHTNING' }
];

// Verify we have 256 unique items
const FONTS_256 = [];
for (let i = 0; i < 256; i++) {
    const item = rawFonts[i] || rawFonts[i % rawFonts.length];
    const hex = '0x' + i.toString(16).toUpperCase().padStart(2, '0');
    FONTS_256.push({
        opcode: i,
        opcodeHex: hex,
        name: item.name,
        family: item.family,
        category: item.cat,
        gFont: item.g,
        sampleNepali: (item.cat === CATEGORIES.NEPALI_DEVANAGARI) ? item.preview : 'डाँफे सिनेमा स्टुडियो',
        sampleEnglish: item.preview || 'DANPHE CINEMA STUDIO'
    });
}

module.exports = {
    FONTS_256,
    CATEGORIES
};
