'use strict';

/**
 * 🦚 Danphe 2 — Samsung ThorVG & LVGL Native Vector Transpiler
 * Transpiles 24-Byte Titan Binary Opcode AST → Native C++ ThorVG / LVGL Graphics
 *
 * SVG Support Matrix (via ThorVG Picture::load):
 *   button, input, box, card, badge, progress, avatar,
 *   image, icon, chart, gauge, slider, toggle, checkbox
 */
class DanpheThorVGTranspiler {
    constructor() {
        this.version = "2.1.0";
    }

    transpileToCpp(astNodes, screenTitle = "DanpheScreen") {
        let code = this._header(screenTitle);

        let counters = {};
        const idx = (tag) => { counters[tag] = (counters[tag] || 0) + 1; return counters[tag]; };

        for (const node of astNodes) {
            const tag = (node.tag || '').toLowerCase();
            code += this._dispatchNode(tag, node, idx, counters);
        }

        code += `    }\n}\n`;
        return code;
    }

    // ── Header ──────────────────────────────────────────────────────────────
    _header(screenTitle) {
        return `/**
 * 🦚 Generated by Danphe 2 Native Engine v2.1
 * Architecture: 100% Native Samsung ThorVG Vector Canvas + LVGL Engine
 * Zero-WebView • Sub-Millisecond Native Rendering
 * SVG Support: All elements via ThorVG Picture::load()
 */

#include <iostream>
#include <vector>
#include <string>
#include <cstring>
#include <lvgl.h>

#if LV_USE_THORVG
#include <thorvg.h>
using namespace tvg;
#endif

// ── Danphe SVG Renderer Bridge ─────────────────────────────────────────────
#ifdef __cplusplus
extern "C" {
#endif
// Forward decl: implemented by danphe-button native module
const char* danphe_get_svg_for_opcode(uint32_t opcode, int w, int h);
#ifdef __cplusplus
}
#endif

// ── Tab touch context ─────────────────────────────────────────────────────
typedef struct {
    int      tab_count;
    int      tab_width;
    int      active;
    int      canvas_w;
    void   (*on_select)(int tab_index, void* user_data);
    void    *user_data;
} danphe_tab_ctx_t;

static void danphe_tabbar_touch_cb(lv_event_t* e) {
    danphe_tab_ctx_t* ctx = (danphe_tab_ctx_t*)lv_event_get_user_data(e);
    if (!ctx) return;
    lv_indev_t* indev = lv_indev_get_act();
    if (!indev) return;
    lv_point_t pt;
    lv_indev_get_point(indev, &pt);
    lv_obj_t* canvas = (lv_obj_t*)lv_event_get_target(e);
    lv_area_t area;
    lv_obj_get_coords(canvas, &area);
    int local_x = pt.x - area.x1;
    int zone = local_x / ctx->tab_width;
    zone = LV_CLAMP(0, zone, ctx->tab_count - 1);
    if (zone != ctx->active) {
        ctx->active = zone;
        if (ctx->on_select) ctx->on_select(zone, ctx->user_data);
    }
}

// ── ThorVG SVG render helper (per-element heap buffer, no sharing) ─────────
static lv_obj_t* danphe_tvg_render(lv_obj_t* parent, const char* svg, int w, int h, int x_ofs, int y_ofs) {
#if LV_USE_THORVG
    // Heap-allocate per element — fixes shared-static-buffer bug
    size_t buf_sz = sizeof(lv_color_t) * w * h;
    uint8_t* buf = (uint8_t*)malloc(buf_sz);
    if (!buf) return nullptr;
    memset(buf, 0, buf_sz);

    lv_obj_t* canvas = lv_canvas_create(parent);
    lv_canvas_set_buffer(canvas, buf, w, h, LV_COLOR_FORMAT_ARGB8888);
    lv_obj_align(canvas, LV_ALIGN_CENTER, x_ofs, y_ofs);

    auto picture = tvg::Picture::gen();
    if (picture->load(svg, strlen(svg), "svg", false) == tvg::Result::Success) {
        auto renderer = tvg::SwCanvas::gen();
        renderer->target((uint32_t*)buf, w, w, h, tvg::ColorSpace::ARGB8888);
        renderer->push(std::move(picture));
        renderer->draw();
        renderer->sync();
        lv_obj_invalidate(canvas);
    }
    lv_obj_add_flag(canvas, LV_OBJ_FLAG_CLICKABLE);
    return canvas;
#else
    return nullptr;
#endif
}


extern "C" {
    void danphe_init_${screenTitle}() {
        lv_obj_t* screen = lv_scr_act();
        lv_obj_set_style_bg_color(screen, lv_color_hex(0x090d16), LV_PART_MAIN);
`;
    }

    // ── Element dispatcher ───────────────────────────────────────────────────
    _dispatchNode(tag, node, idx, counters) {
        // All elements: if svg or opcode present → ThorVG path
        const hasSVG = node.svg || node.opcode != null;

        switch (tag) {
            case 'button': case 'btn':      return this._button(node, idx('btn'), hasSVG);
            case 'input': case 'textfield': return this._input(node, idx('input'), hasSVG);
            case 'box': case 'div':
            case 'card': case 'container': return this._box(node, idx('box'), hasSVG);
            case 'badge': case 'chip':      return this._badge(node, idx('badge'), hasSVG);
            case 'progress': case 'bar':    return this._progress(node, idx('prog'), hasSVG);
            case 'avatar': case 'image':
            case 'img':                     return this._image(node, idx('img'), hasSVG);
            case 'icon':                    return this._icon(node, idx('icon'), hasSVG);
            case 'gauge': case 'chart':     return this._gauge(node, idx('gauge'), hasSVG);
            case 'toggle': case 'switch':   return this._toggle(node, idx('toggle'), hasSVG);
            case 'checkbox': case 'check':  return this._checkbox(node, idx('chk'), hasSVG);
            case 'slider':                  return this._slider(node, idx('slider'), hasSVG);
            case 'tabbar': case 'tabs':
            case 'tab':                     return this._tabbar(node, idx('tab'));
            case 'h1': case 'h2': case 'h3':
            case 'p': case 'span':
            case 'label': case 'text':      return this._label(node, idx('lbl'));
            default:                        return this._box(node, idx('box'), hasSVG);
        }
    }

    // ── TabBar ───────────────────────────────────────────────────────────────
    _tabbar(n, i) {
        const tabs    = n.tabs || ['Tab 1', 'Tab 2'];
        const active  = n.active || 0;
        const style   = n.style || 'solid';   // 'solid' | 'pill' | 'underline'
        const palette = n.palette || 'primary';
        const tabW    = n.tabWidth || 120;
        const h       = n.height || 44;
        const W       = tabW * tabs.length;
        const yOfs    = (i - 1) * (h + 12);

        // Generate DanpheTabBar SVG at build time (compile-time, Node.js side)
        // native:true → feDropShadow हटाउँछ (ThorVG ले support gardaina)
        let svgData = null;
        const candidatePaths = [
            '../../danphe-button/dist/danphe-button.cjs.js',
            '../../../danphe-button/dist/danphe-button.cjs.js',
            'D:/danphe-button/dist/danphe-button.cjs.js',
        ];
        for (const p of candidatePaths) {
            try {
                const mod = require(p);
                if (mod.DanpheTabBar) {
                    svgData = mod.DanpheTabBar[style](tabs, active, {
                        palette, tabWidth: tabW, height: h,
                        native: true  // ← feDropShadow skip — ThorVG safe
                    });
                    break;
                }
            } catch (e) { /* try next */ }
        }

        if (svgData) {
            return `
        // [TVG] TabBar #${i} — DanpheTabBar SVG via ThorVG (${style}/${palette}, ${tabs.length} tabs)
#if LV_USE_THORVG
        {
            lv_obj_t* tabcanvas_${i} = danphe_tvg_render(screen, ${this._escapeSvg(svgData)}, ${W}, ${h}, 0, ${yOfs});

            // ── Touch zone wiring: X position → tab index ──────────────────
            static danphe_tab_ctx_t tab_ctx_${i} = {
                .tab_count = ${tabs.length},
                .tab_width = ${tabW},
                .active    = ${active},
                .canvas_w  = ${W},
                .on_select = nullptr,   // replace with your handler
                .user_data = nullptr
            };
            if (tabcanvas_${i}) {
                lv_obj_add_event_cb(tabcanvas_${i}, danphe_tabbar_touch_cb,
                    LV_EVENT_CLICKED, &tab_ctx_${i});
            }
            // Tab labels: ${tabs.map((t,ti)=>`[${ti}]="${t}"`).join(', ')}
        }
#else
        // Fallback: native LVGL tabview
        ${this._lvglTabview(tabs, active, W, h, yOfs, i)}
#endif
`;
        }

        // No SVG available — pure LVGL tabview
        return this._lvglTabview(tabs, active, W, h, yOfs, i);
    }

    _lvglTabview(tabs, active, W, h, yOfs, i) {
        let code = `
        // [0x80] TabBar #${i} — Native LVGL tabview (${tabs.length} tabs)
        lv_obj_t* tv_${i} = lv_tabview_create(screen, LV_DIR_TOP, ${h});
        lv_obj_set_width(tv_${i}, ${W});
        lv_obj_align(tv_${i}, LV_ALIGN_TOP_MID, 0, ${yOfs});
        lv_obj_set_style_bg_color(tv_${i}, lv_color_hex(0x0f172a), LV_PART_MAIN);
        lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(tv_${i}), lv_color_hex(0x1e293b), LV_PART_MAIN);
`;
        tabs.forEach((label, ti) => {
            code += `        lv_obj_t* tab_${i}_${ti} = lv_tabview_add_tab(tv_${i}, "${label.replace(/"/g, '\\"')}");\n`;
            if (ti === active) {
                code += `        lv_tabview_set_act(tv_${i}, ${ti}, LV_ANIM_OFF);\n`;
            }
        });
        return code;
    }

    // ── SVG render block (ThorVG) ────────────────────────────────────────────
    _tvgBlock(n, name, w, h, yOfs) {
        const svg = n.svg ? this._escapeSvg(n.svg)
                          : `danphe_get_svg_for_opcode(0x${(n.opcode||0).toString(16).toUpperCase().padStart(8,'0')}, ${w}, ${h})`;
        return `
        // [TVG] ${name} — ThorVG SVG (opcode: 0x${(n.opcode||0).toString(16).toUpperCase().padStart(8,'0')})
#if LV_USE_THORVG
        danphe_tvg_render(screen, ${svg}, ${w}, ${h}, 0, ${yOfs});
#else
`;
    }
    _tvgBlockEnd() { return `#endif\n`; }

    _emitGradientAndShadow(n, varName) {
        let code = '';
        const cls = String(n.className || n.class || '');
        const style = String(n.style || '');
        const gradAttr = n.gradient || n['data-titan-gradient'] || '';
        const shadowAttr = n.shadow || n['data-titan-shadow'] || '';

        // Check for gradient
        let gradColor = null;
        if (gradAttr || style.includes('linear-gradient') || cls.includes('bg-gradient-') || cls.includes('from-')) {
            const toMatch = cls.match(/\bto-([a-z]+)-([0-9]+)\b/);
            const colorMap = {
                blue: '0x2563eb', indigo: '0x4f46e5', purple: '0x9333ea',
                pink: '0xdb2777', rose: '0xe11d48', red: '0xdc2626',
                orange: '0xea580c', amber: '0xd97706', yellow: '0xca8a04',
                emerald: '0x059669', teal: '0x0d9488', cyan: '0x0891b2',
                sky: '0x0284c7'
            };
            if (toMatch && colorMap[toMatch[1]]) {
                gradColor = colorMap[toMatch[1]];
            } else {
                gradColor = '0x1e1b4b';
            }
            code += `        lv_obj_set_style_bg_grad_color(${varName}, lv_color_hex(${gradColor}), LV_PART_MAIN);\n`;
            code += `        lv_obj_set_style_bg_grad_dir(${varName}, LV_GRAD_DIR_HOR, LV_PART_MAIN);\n`;
        }

        // Check for shadow
        if (shadowAttr || style.includes('box-shadow') || cls.includes('shadow')) {
            let width = 16, ofsY = 8, opa = 'LV_OPA_50';
            if (cls.includes('shadow-2xl')) { width = 28; ofsY = 14; opa = 'LV_OPA_70'; }
            else if (cls.includes('shadow-xl')) { width = 22; ofsY = 11; opa = 'LV_OPA_60'; }
            else if (cls.includes('shadow-lg')) { width = 16; ofsY = 8; opa = 'LV_OPA_50'; }
            else if (cls.includes('shadow-md')) { width = 10; ofsY = 5; opa = 'LV_OPA_40'; }

            code += `        lv_obj_set_style_shadow_width(${varName}, ${width}, LV_PART_MAIN);\n`;
            code += `        lv_obj_set_style_shadow_ofs_y(${varName}, ${ofsY}, LV_PART_MAIN);\n`;
            code += `        lv_obj_set_style_shadow_color(${varName}, lv_color_hex(0x000000), LV_PART_MAIN);\n`;
            code += `        lv_obj_set_style_shadow_opa(${varName}, ${opa}, LV_PART_MAIN);\n`;
        }

        return code;
    }

    // ── Button ───────────────────────────────────────────────────────────────
    _button(n, i, hasSVG) {
        const w = n.width || 240, h = n.height || 56, y = (i - 1) * (h + 12);
        const text = (n.text || 'BUTTON').replace(/"/g, '\\"');
        const col = n.color || '0x0284c7';
        if (hasSVG) {
            return this._tvgBlock(n, `Button #${i}`, w, h, y) +
                `        // Fallback plain button\n` +
                `        lv_obj_t* btn_${i} = lv_btn_create(screen);\n` +
                `        lv_obj_set_size(btn_${i}, ${w}, ${h});\n` +
                `        lv_obj_align(btn_${i}, LV_ALIGN_CENTER, 0, ${y});\n` +
                `        lv_obj_set_style_bg_color(btn_${i}, lv_color_hex(${col}), LV_PART_MAIN);\n` +
                this._emitGradientAndShadow(n, `btn_${i}`) +
                `        lv_obj_set_style_radius(btn_${i}, 12, LV_PART_MAIN);\n` +
                `        lv_obj_t* lbl_b${i} = lv_label_create(btn_${i});\n` +
                `        lv_label_set_text(lbl_b${i}, "${text}");\n` +
                `        lv_obj_center(lbl_b${i});\n` +
                this._tvgBlockEnd();
        }
        return `
        // [0x10] Button #${i}
        lv_obj_t* btn_${i} = lv_btn_create(screen);
        lv_obj_set_size(btn_${i}, ${w}, ${h});
        lv_obj_align(btn_${i}, LV_ALIGN_CENTER, 0, ${y});
        lv_obj_set_style_bg_color(btn_${i}, lv_color_hex(${col}), LV_PART_MAIN);
${this._emitGradientAndShadow(n, `btn_${i}`)}        lv_obj_set_style_radius(btn_${i}, 12, LV_PART_MAIN);
        lv_obj_t* lbl_b${i} = lv_label_create(btn_${i});
        lv_label_set_text(lbl_b${i}, "${text}");
        lv_obj_center(lbl_b${i});
`;
    }

    // ── Input / TextField ────────────────────────────────────────────────────
    _input(n, i, hasSVG) {
        const w = n.width || 240, h = n.height || 44, y = (i - 1) * (h + 10);
        const ph = (n.placeholder || n.text || '').replace(/"/g, '\\"');
        if (hasSVG) {
            return this._tvgBlock(n, `Input #${i}`, w, h, y) +
                `        lv_obj_t* ta_${i} = lv_textarea_create(screen);\n` +
                `        lv_obj_set_size(ta_${i}, ${w}, ${h});\n` +
                `        lv_obj_align(ta_${i}, LV_ALIGN_CENTER, 0, ${y});\n` +
                `        lv_textarea_set_placeholder_text(ta_${i}, "${ph}");\n` +
                this._tvgBlockEnd();
        }
        return `
        // [0x20] Input/TextField #${i}
        lv_obj_t* ta_${i} = lv_textarea_create(screen);
        lv_obj_set_size(ta_${i}, ${w}, ${h});
        lv_obj_align(ta_${i}, LV_ALIGN_CENTER, 0, ${y});
        lv_textarea_set_placeholder_text(ta_${i}, "${ph}");
        lv_obj_set_style_bg_color(ta_${i}, lv_color_hex(0x1e293b), LV_PART_MAIN);
        lv_obj_set_style_text_color(ta_${i}, lv_color_hex(0xf8fafc), LV_PART_MAIN);
        lv_obj_set_style_radius(ta_${i}, 8, LV_PART_MAIN);
        lv_obj_set_style_border_color(ta_${i}, lv_color_hex(0x334155), LV_PART_MAIN);
`;
    }

    // ── Box / Card / Container ───────────────────────────────────────────────
    _box(n, i, hasSVG) {
        const w = n.width || 280, h = n.height || 120, y = (i - 1) * (h + 16);
        const col = n.color || '0x1e293b';
        if (hasSVG) {
            return this._tvgBlock(n, `Box #${i}`, w, h, y) +
                `        lv_obj_t* box_${i} = lv_obj_create(screen);\n` +
                `        lv_obj_set_size(box_${i}, ${w}, ${h});\n` +
                `        lv_obj_align(box_${i}, LV_ALIGN_CENTER, 0, ${y});\n` +
                this._tvgBlockEnd();
        }
        return `
        // [0x30] Box/Card #${i}
        lv_obj_t* box_${i} = lv_obj_create(screen);
        lv_obj_set_size(box_${i}, ${w}, ${h});
        lv_obj_align(box_${i}, LV_ALIGN_CENTER, 0, ${y});
        lv_obj_set_style_bg_color(box_${i}, lv_color_hex(${col}), LV_PART_MAIN);
${this._emitGradientAndShadow(n, `box_${i}`)}        lv_obj_set_style_radius(box_${i}, 16, LV_PART_MAIN);
        lv_obj_set_style_border_color(box_${i}, lv_color_hex(0x334155), LV_PART_MAIN);
        lv_obj_set_style_border_width(box_${i}, 1, LV_PART_MAIN);
        lv_obj_set_style_pad_all(box_${i}, 16, LV_PART_MAIN);
`;
    }

    // ── Badge / Chip ─────────────────────────────────────────────────────────
    _badge(n, i, hasSVG) {
        const w = n.width || 80, h = n.height || 28, y = (i - 1) * 36;
        const text = (n.text || 'BADGE').replace(/"/g, '\\"');
        const col = n.color || '0x0284c7';
        if (hasSVG) {
            return this._tvgBlock(n, `Badge #${i}`, w, h, y) +
                `        lv_obj_t* badge_${i} = lv_label_create(screen);\n` +
                `        lv_label_set_text(badge_${i}, "${text}");\n` +
                this._tvgBlockEnd();
        }
        return `
        // [0x31] Badge/Chip #${i}
        lv_obj_t* badge_${i} = lv_label_create(screen);
        lv_label_set_text(badge_${i}, "${text}");
        lv_obj_set_style_text_color(badge_${i}, lv_color_hex(0xffffff), LV_PART_MAIN);
        lv_obj_set_style_bg_color(badge_${i}, lv_color_hex(${col}), LV_PART_MAIN);
        lv_obj_set_style_bg_opa(badge_${i}, LV_OPA_COVER, LV_PART_MAIN);
        lv_obj_set_style_radius(badge_${i}, 9999, LV_PART_MAIN);
        lv_obj_set_style_pad_hor(badge_${i}, 10, LV_PART_MAIN);
        lv_obj_set_style_pad_ver(badge_${i}, 4, LV_PART_MAIN);
        lv_obj_align(badge_${i}, LV_ALIGN_TOP_LEFT, 16, ${y + 16});
`;
    }

    // ── Progress Bar ─────────────────────────────────────────────────────────
    _progress(n, i, hasSVG) {
        const w = n.width || 240, h = n.height || 16, y = (i - 1) * 36;
        const val = n.value || 50;
        const col = n.color || '0x0284c7';
        if (hasSVG) {
            return this._tvgBlock(n, `Progress #${i}`, w, h, y) +
                `        lv_obj_t* bar_${i} = lv_bar_create(screen);\n` +
                `        lv_obj_set_size(bar_${i}, ${w}, ${h});\n` +
                `        lv_bar_set_value(bar_${i}, ${val}, LV_ANIM_ON);\n` +
                this._tvgBlockEnd();
        }
        return `
        // [0x40] Progress Bar #${i}
        lv_obj_t* bar_${i} = lv_bar_create(screen);
        lv_obj_set_size(bar_${i}, ${w}, ${h});
        lv_obj_align(bar_${i}, LV_ALIGN_CENTER, 0, ${y});
        lv_obj_set_style_bg_color(bar_${i}, lv_color_hex(0x1e293b), LV_PART_MAIN);
        lv_obj_set_style_bg_color(bar_${i}, lv_color_hex(${col}), LV_PART_INDICATOR);
        lv_obj_set_style_radius(bar_${i}, 8, LV_PART_MAIN);
        lv_bar_set_value(bar_${i}, ${val}, LV_ANIM_ON);
`;
    }

    // ── Image / Avatar ───────────────────────────────────────────────────────
    _image(n, i, hasSVG) {
        const w = n.width || 64, h = n.height || 64, y = (i - 1) * (h + 8);
        if (hasSVG) {
            return this._tvgBlock(n, `Image/Avatar #${i}`, w, h, y) +
                `        // No fallback image without asset path\n` +
                this._tvgBlockEnd();
        }
        const src = n.src ? `"${n.src}"` : 'NULL';
        return `
        // [0x50] Image/Avatar #${i}
        lv_obj_t* img_${i} = lv_img_create(screen);
        lv_img_set_src(img_${i}, ${src});
        lv_obj_set_size(img_${i}, ${w}, ${h});
        lv_obj_align(img_${i}, LV_ALIGN_CENTER, 0, ${y});
        lv_obj_set_style_radius(img_${i}, 9999, LV_PART_MAIN);
        lv_obj_set_style_clip_corner(img_${i}, true, LV_PART_MAIN);
`;
    }

    // ── Icon ─────────────────────────────────────────────────────────────────
    _icon(n, i, hasSVG) {
        const w = n.width || 32, h = n.height || 32, y = (i - 1) * 40;
        if (hasSVG) {
            return this._tvgBlock(n, `Icon #${i}`, w, h, y) +
                `        // No plain fallback for icons without SVG\n` +
                this._tvgBlockEnd();
        }
        const text = n.text || '?';
        return `
        // [0x51] Icon #${i}
        lv_obj_t* icon_${i} = lv_label_create(screen);
        lv_label_set_text(icon_${i}, "${text}");
        lv_obj_set_style_text_font(icon_${i}, &lv_font_montserrat_24, LV_PART_MAIN);
        lv_obj_set_style_text_color(icon_${i}, lv_color_hex(0x38bdf8), LV_PART_MAIN);
        lv_obj_align(icon_${i}, LV_ALIGN_CENTER, 0, ${y});
`;
    }

    // ── Gauge / Chart ────────────────────────────────────────────────────────
    _gauge(n, i, hasSVG) {
        const w = n.width || 200, h = n.height || 200, y = (i - 1) * (h + 16);
        const val = n.value || 0;
        if (hasSVG) {
            return this._tvgBlock(n, `Gauge #${i}`, w, h, y) +
                `        lv_obj_t* arc_${i} = lv_arc_create(screen);\n` +
                `        lv_obj_set_size(arc_${i}, ${w}, ${h});\n` +
                `        lv_arc_set_value(arc_${i}, ${val});\n` +
                this._tvgBlockEnd();
        }
        return `
        // [0x60] Gauge/Arc #${i}
        lv_obj_t* arc_${i} = lv_arc_create(screen);
        lv_obj_set_size(arc_${i}, ${w}, ${h});
        lv_obj_align(arc_${i}, LV_ALIGN_CENTER, 0, ${y});
        lv_obj_set_style_arc_color(arc_${i}, lv_color_hex(0x38bdf8), LV_PART_INDICATOR);
        lv_arc_set_rotation(arc_${i}, 135);
        lv_arc_set_bg_angles(arc_${i}, 0, 270);
        lv_arc_set_value(arc_${i}, ${val});
`;
    }

    // ── Slider ───────────────────────────────────────────────────────────────
    _slider(n, i, hasSVG) {
        const w = n.width || 240, h = n.height || 18, y = (i - 1) * 36;
        const val = n.value || 50;
        const col = n.color || '0x38bdf8';
        if (hasSVG) {
            return this._tvgBlock(n, `Slider #${i}`, w, h, y) +
                `        lv_obj_t* sl_${i} = lv_slider_create(screen);\n` +
                `        lv_obj_set_size(sl_${i}, ${w}, ${h});\n` +
                `        lv_slider_set_value(sl_${i}, ${val}, LV_ANIM_OFF);\n` +
                this._tvgBlockEnd();
        }
        return `
        // [0x23] Slider #${i}
        lv_obj_t* sl_${i} = lv_slider_create(screen);
        lv_obj_set_size(sl_${i}, ${w}, ${h});
        lv_obj_align(sl_${i}, LV_ALIGN_CENTER, 0, ${y});
        lv_obj_set_style_bg_color(sl_${i}, lv_color_hex(${col}), LV_PART_INDICATOR);
        lv_obj_set_style_bg_color(sl_${i}, lv_color_hex(${col}), LV_PART_KNOB);
        lv_slider_set_value(sl_${i}, ${val}, LV_ANIM_OFF);
`;
    }

    // ── Toggle / Switch ──────────────────────────────────────────────────────
    _toggle(n, i, hasSVG) {
        const w = n.width || 60, h = n.height || 32, y = (i - 1) * 44;
        const on = n.value || n.checked || false;
        if (hasSVG) {
            return this._tvgBlock(n, `Toggle #${i}`, w, h, y) +
                `        lv_obj_t* sw_${i} = lv_switch_create(screen);\n` +
                `        lv_obj_align(sw_${i}, LV_ALIGN_CENTER, 0, ${y});\n` +
                (on ? `        lv_obj_add_state(sw_${i}, LV_STATE_CHECKED);\n` : '') +
                this._tvgBlockEnd();
        }
        return `
        // [0x70] Toggle/Switch #${i}
        lv_obj_t* sw_${i} = lv_switch_create(screen);
        lv_obj_align(sw_${i}, LV_ALIGN_CENTER, 0, ${y});
        lv_obj_set_style_bg_color(sw_${i}, lv_color_hex(0x0284c7), LV_PART_INDICATOR);
        ${on ? `lv_obj_add_state(sw_${i}, LV_STATE_CHECKED);` : ''}
`;
    }

    // ── Checkbox ─────────────────────────────────────────────────────────────
    _checkbox(n, i, hasSVG) {
        const text = (n.text || n.label || '').replace(/"/g, '\\"');
        const y = (i - 1) * 36;
        const checked = n.value || n.checked || false;
        if (hasSVG) {
            return this._tvgBlock(n, `Checkbox #${i}`, 140, 36, y) +
                `        lv_obj_t* cb_${i} = lv_checkbox_create(screen);\n` +
                `        lv_checkbox_set_text(cb_${i}, "${text}");\n` +
                (checked ? `        lv_obj_add_state(cb_${i}, LV_STATE_CHECKED);\n` : '') +
                this._tvgBlockEnd();
        }
        return `
        // [0x71] Checkbox #${i}
        lv_obj_t* cb_${i} = lv_checkbox_create(screen);
        lv_checkbox_set_text(cb_${i}, "${text}");
        lv_obj_align(cb_${i}, LV_ALIGN_LEFT_MID, 16, ${y});
        lv_obj_set_style_bg_color(cb_${i}, lv_color_hex(0x0284c7), LV_PART_INDICATOR | LV_STATE_CHECKED);
        ${checked ? `lv_obj_add_state(cb_${i}, LV_STATE_CHECKED);` : ''}
`;
    }

    // ── Label / Text ─────────────────────────────────────────────────────────
    _label(n, i) {
        const text = (n.text || '').replace(/"/g, '\\"');
        const stateKey = n.stateKey || '';
        const col = n.color || '0x38bdf8';
        return `
        // [0x14] Label #${i}
        lv_obj_t* lbl_${i} = lv_label_create(screen);
        ${stateKey
            ? `// State Reactive -> ${stateKey}\n        lv_label_set_text(lbl_${i}, "[State: ${stateKey}]");`
            : `lv_label_set_text(lbl_${i}, "${text}");`}
        lv_obj_set_style_text_color(lbl_${i}, lv_color_hex(${col}), LV_PART_MAIN);
        lv_obj_align(lbl_${i}, LV_ALIGN_TOP_MID, 0, ${(i - 1) * 35 + 25});
`;
    }

    // ── Helpers ──────────────────────────────────────────────────────────────
    _escapeSvg(svg) {
        const e = svg.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,' ').replace(/\r/g,'');
        return `"${e}"`;
    }
}

module.exports = { DanpheThorVGTranspiler };
