'use strict';

/**
 * 🦚 Danphe 2 — Samsung ThorVG & LVGL Native Vector Transpiler
 * Transpiles 24-Byte Titan Binary Opcode AST into Native C++ ThorVG / LVGL Graphics
 */
class DanpheThorVGTranspiler {
    constructor() {
        this.version = "2.0.0";
    }

    /**
     * Transpile Titan Binary / Node AST to Pure Embedded C++ ThorVG Vector Commands
     */
    transpileToCpp(astNodes, screenTitle = "DanpheScreen") {
        let code = `/**
 * 🦚 Generated by Danphe 2 Native Engine
 * Architecture: 100% Native Samsung ThorVG Vector Canvas + LVGL Engine
 * Zero-WebView • Sub-Millisecond Native Rendering
 */

#include <iostream>
#include <vector>
#include <string>
#include <lvgl.h>

#if LV_USE_THORVG
#include <thorvg.h>
using namespace tvg;
#endif

// Dolphin Native C++ State Bridge
extern "C" {
    void danphe_init_${screenTitle}() {
        lv_obj_t* screen = lv_scr_act();
        lv_obj_set_style_bg_color(screen, lv_color_hex(0x090d16), LV_PART_MAIN);

#if LV_USE_THORVG
        // Initialize Samsung ThorVG Canvas
        auto canvas = SwCanvas::gen();
#endif
`;

        let btnIndex = 0;
        let lblIndex = 0;
        let sliderIndex = 0;

        for (const node of astNodes) {
            const tag = (node.tag || '').toLowerCase();
            const text = node.text || '';
            const stateKey = node.stateKey || '';

            if (tag === 'button' || tag === 'btn') {
                btnIndex++;
                code += `
        // [0x10] Native Button Component #${btnIndex}
        lv_obj_t* btn_${btnIndex} = lv_btn_create(screen);
        lv_obj_set_size(btn_${btnIndex}, 180, 50);
        lv_obj_align(btn_${btnIndex}, LV_ALIGN_CENTER, 0, ${(btnIndex - 1) * 60});
        lv_obj_set_style_bg_color(btn_${btnIndex}, lv_color_hex(0x0284c7), LV_PART_MAIN);
        lv_obj_set_style_radius(btn_${btnIndex}, 12, LV_PART_MAIN);
`;
                if (text) {
                    code += `        lv_obj_t* btn_lbl_${btnIndex} = lv_label_create(btn_${btnIndex});
        lv_label_set_text(btn_lbl_${btnIndex}, "${text.replace(/"/g, '\\"')}");
        lv_obj_center(btn_lbl_${btnIndex});\n`;
                }
            } else if (tag === 'h1' || tag === 'h2' || tag === 'p' || tag === 'span' || tag === 'label') {
                lblIndex++;
                code += `
        // [0x14/0x13] Native Text / Label #${lblIndex}
        lv_obj_t* lbl_${lblIndex} = lv_label_create(screen);
`;
                if (stateKey) {
                    code += `        // State Reactive Key -> ${stateKey}
        lv_label_set_text(lbl_${lblIndex}, "[State: ${stateKey}]");
`;
                } else if (text) {
                    code += `        lv_label_set_text(lbl_${lblIndex}, "${text.replace(/"/g, '\\"')}");\n`;
                }
                code += `        lv_obj_set_style_text_color(lbl_${lblIndex}, lv_color_hex(0x38bdf8), LV_PART_MAIN);
        lv_obj_align(lbl_${lblIndex}, LV_ALIGN_TOP_MID, 0, ${(lblIndex - 1) * 35 + 25});
`;
            } else if (tag === 'slider') {
                sliderIndex++;
                code += `
        // [0x23] Native Slider Control #${sliderIndex}
        lv_obj_t* slider_${sliderIndex} = lv_slider_create(screen);
        lv_obj_set_size(slider_${sliderIndex}, 240, 18);
        lv_obj_align(slider_${sliderIndex}, LV_ALIGN_CENTER, 0, ${(btnIndex * 60) + 30});
        lv_obj_set_style_bg_color(slider_${sliderIndex}, lv_color_hex(0x38bdf8), LV_PART_INDICATOR);
`;
            }
        }

        code += `    }
}
`;
        return code;
    }
}

module.exports = { DanpheThorVGTranspiler };
