'use strict';

const { TITAN_TEXT_BITS } = require('./TitanTextRegisters');

const PIXELLAB_PRESETS = {
    cinema_gold: {
        name: '24K Cinema Gold',
        category: '3D Gold',
        bitmask1: TITAN_TEXT_BITS.BOLD | TITAN_TEXT_BITS.ALL_CAPS | TITAN_TEXT_BITS.STROKE_ACTIVE | TITAN_TEXT_BITS.DROP_SHADOW | TITAN_TEXT_BITS.EMBOSS_LIGHTING,
        bitmask2: TITAN_TEXT_BITS.EXTRUDE_3D | TITAN_TEXT_BITS.METALLIC_GRADIENT | TITAN_TEXT_BITS.FLOOR_SHADOW_3D,
        fontFamily: 'Impact, "Cinzel", "Times New Roman", serif',
        fontSize: 64, tracking: 4, lineHeight: 1.1,
        fillType: 'gradient', fillColor: '#fbbf24',
        gradient: 'linear-gradient(180deg, #fef08a 0%, #facc15 35%, #b45309 70%, #d97706 100%)',
        strokeWidth: 1.5, strokeColor: '#fef08a', dualStrokeWidth: 3, dualStrokeColor: '#451a03',
        shadowBlur: 18, shadowColor: 'rgba(0,0,0,0.95)', shadowDist: 8, shadowAngle: 45,
        innerShadowBlur: 4, innerShadowDist: 2, innerShadowColor: 'rgba(255,255,255,0.4)',
        extrudeDepth: 8, extrudeColor: '#78350f', extrudeDarken: 45,
        rot3dX: 15, rot3dY: -10, rotZ: 0, bendCurve: 0,
        glowSpread: 6, glowColor: '#f59e0b',
        bannerColor: 'rgba(0,0,0,0.6)', bannerRadius: 8, bannerPadX: 16, bannerPadY: 8
    },
    cyberpunk_neon: {
        name: 'Cyberpunk 2077 Neon',
        category: 'Glow FX',
        bitmask1: TITAN_TEXT_BITS.BOLD | TITAN_TEXT_BITS.ITALIC | TITAN_TEXT_BITS.ALL_CAPS | TITAN_TEXT_BITS.GLOW_ACTIVE | TITAN_TEXT_BITS.STROKE_ACTIVE | TITAN_TEXT_BITS.DUAL_STROKE,
        bitmask2: TITAN_TEXT_BITS.METALLIC_GRADIENT | TITAN_TEXT_BITS.NEON_PULSE_FX,
        fontFamily: '"Arial Black", sans-serif',
        fontSize: 58, tracking: 6, lineHeight: 1.1,
        fillType: 'gradient', fillColor: '#00f0ff',
        gradient: 'linear-gradient(180deg, #e0e7ff 0%, #38bdf8 40%, #00f0ff 100%)',
        strokeWidth: 1.5, strokeColor: '#f43f5e', dualStrokeWidth: 4, dualStrokeColor: 'rgba(244,63,94,0.4)',
        shadowBlur: 24, shadowColor: '#00f0ff', shadowDist: 0, shadowAngle: 0,
        innerShadowBlur: 0, innerShadowDist: 0, innerShadowColor: 'transparent',
        extrudeDepth: 0, extrudeColor: '#000', extrudeDarken: 0,
        rot3dX: 0, rot3dY: 0, rotZ: -2, bendCurve: 0,
        glowSpread: 18, glowColor: '#00f0ff',
        bannerColor: 'rgba(6,11,22,0.85)', bannerRadius: 10, bannerPadX: 20, bannerPadY: 10
    },
    netflix_trailer: {
        name: 'Netflix Red Ultra',
        category: 'Clean Cinema',
        bitmask1: TITAN_TEXT_BITS.BOLD | TITAN_TEXT_BITS.ALL_CAPS | TITAN_TEXT_BITS.DROP_SHADOW,
        bitmask2: 0,
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        fontSize: 52, tracking: 16, lineHeight: 1.2,
        fillType: 'solid', fillColor: '#e50914',
        gradient: 'none',
        strokeWidth: 0, strokeColor: 'transparent', dualStrokeWidth: 0, dualStrokeColor: 'transparent',
        shadowBlur: 16, shadowColor: 'rgba(229,9,20,0.7)', shadowDist: 4, shadowAngle: 90,
        innerShadowBlur: 0, innerShadowDist: 0, innerShadowColor: 'transparent',
        extrudeDepth: 0, extrudeColor: '#000', extrudeDarken: 0,
        rot3dX: 0, rot3dY: 0, rotZ: 0, bendCurve: 0,
        glowSpread: 0, glowColor: '#e50914',
        bannerColor: 'transparent', bannerRadius: 0, bannerPadX: 0, bannerPadY: 0
    },
    retro_synthwave: {
        name: '80s Sunset Synth',
        category: 'Vintage',
        bitmask1: TITAN_TEXT_BITS.BOLD | TITAN_TEXT_BITS.ITALIC | TITAN_TEXT_BITS.ALL_CAPS | TITAN_TEXT_BITS.STROKE_ACTIVE | TITAN_TEXT_BITS.GLOW_ACTIVE,
        bitmask2: TITAN_TEXT_BITS.EXTRUDE_3D | TITAN_TEXT_BITS.METALLIC_GRADIENT,
        fontFamily: 'Impact, "Trebuchet MS", sans-serif',
        fontSize: 60, tracking: 4, lineHeight: 1.1,
        fillType: 'gradient', fillColor: '#38bdf8',
        gradient: 'linear-gradient(180deg, #38bdf8 0%, #a855f7 35%, #ec4899 70%, #fbbf24 100%)',
        strokeWidth: 2, strokeColor: '#f43f5e', dualStrokeWidth: 2, dualStrokeColor: '#1e1b4b',
        shadowBlur: 20, shadowColor: '#ec4899', shadowDist: 5, shadowAngle: 60,
        innerShadowBlur: 0, innerShadowDist: 0, innerShadowColor: 'transparent',
        extrudeDepth: 5, extrudeColor: '#831843', extrudeDarken: 50,
        rot3dX: 12, rot3dY: 0, rotZ: -3, bendCurve: 10,
        glowSpread: 14, glowColor: '#ec4899',
        bannerColor: 'rgba(15,7,30,0.85)', bannerRadius: 12, bannerPadX: 18, bannerPadY: 8
    },
    curved_badge: {
        name: 'Curved University Badge',
        category: 'Emblem',
        bitmask1: TITAN_TEXT_BITS.BOLD | TITAN_TEXT_BITS.ALL_CAPS | TITAN_TEXT_BITS.STROKE_ACTIVE | TITAN_TEXT_BITS.DROP_SHADOW,
        bitmask2: TITAN_TEXT_BITS.CURVED_BEND | TITAN_TEXT_BITS.METALLIC_GRADIENT,
        fontFamily: 'Georgia, serif',
        fontSize: 50, tracking: 8, lineHeight: 1.1,
        fillType: 'gradient', fillColor: '#38bdf8',
        gradient: 'linear-gradient(180deg, #bae6fd 0%, #38bdf8 60%, #0284c7 100%)',
        strokeWidth: 2, strokeColor: '#082f49', dualStrokeWidth: 0, dualStrokeColor: 'transparent',
        shadowBlur: 12, shadowColor: 'rgba(0,0,0,0.8)', shadowDist: 4, shadowAngle: 90,
        innerShadowBlur: 0, innerShadowDist: 0, innerShadowColor: 'transparent',
        extrudeDepth: 3, extrudeColor: '#0c4a6e', extrudeDarken: 30,
        rot3dX: 0, rot3dY: 0, rotZ: 0, bendCurve: 35,
        glowSpread: 4, glowColor: '#38bdf8',
        bannerColor: 'transparent', bannerRadius: 0, bannerPadX: 0, bannerPadY: 0
    },
    himalaya_gold: {
        name: 'Himalayan Calligraphy',
        category: 'Nepali Heritage',
        bitmask1: TITAN_TEXT_BITS.BOLD | TITAN_TEXT_BITS.STROKE_ACTIVE | TITAN_TEXT_BITS.GLOW_ACTIVE | TITAN_TEXT_BITS.DROP_SHADOW,
        bitmask2: TITAN_TEXT_BITS.EXTRUDE_3D | TITAN_TEXT_BITS.METALLIC_GRADIENT | TITAN_TEXT_BITS.BACKDROP_BANNER,
        fontFamily: '"Mukti", "Preeti", "Kalimati", Georgia, serif',
        fontSize: 56, tracking: 2, lineHeight: 1.2,
        fillType: 'gradient', fillColor: '#ea580c',
        gradient: 'linear-gradient(180deg, #fef08a 0%, #fed7aa 30%, #fb923c 65%, #c2410c 100%)',
        strokeWidth: 1.5, strokeColor: '#fef08a', dualStrokeWidth: 2, dualStrokeColor: '#431407',
        shadowBlur: 16, shadowColor: 'rgba(0,0,0,0.9)', shadowDist: 6, shadowAngle: 45,
        innerShadowBlur: 3, innerShadowDist: 2, innerShadowColor: 'rgba(255,255,255,0.5)',
        extrudeDepth: 4, extrudeColor: '#7c2d12', extrudeDarken: 40,
        rot3dX: 8, rot3dY: -4, rotZ: 0, bendCurve: 0,
        glowSpread: 10, glowColor: '#f97316',
        bannerColor: 'rgba(41,10,2,0.85)', bannerRadius: 10, bannerPadX: 18, bannerPadY: 8
    },
    glassmorphism_frost: {
        name: 'Glassmorphism Frost',
        category: 'Modern Glass',
        bitmask1: TITAN_TEXT_BITS.BOLD | TITAN_TEXT_BITS.DROP_SHADOW | TITAN_TEXT_BITS.INNER_SHADOW,
        bitmask2: TITAN_TEXT_BITS.BACKDROP_BANNER | TITAN_TEXT_BITS.METALLIC_GRADIENT,
        fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        fontSize: 54, tracking: 6, lineHeight: 1.1,
        fillType: 'gradient', fillColor: '#ffffff',
        gradient: 'linear-gradient(135deg, rgba(255,255,255,0.95) 0%, rgba(255,255,255,0.5) 100%)',
        strokeWidth: 1, strokeColor: 'rgba(255,255,255,0.6)', dualStrokeWidth: 0, dualStrokeColor: 'transparent',
        shadowBlur: 18, shadowColor: 'rgba(0,0,0,0.5)', shadowDist: 6, shadowAngle: 45,
        innerShadowBlur: 4, innerShadowDist: 2, innerShadowColor: 'rgba(255,255,255,0.9)',
        extrudeDepth: 0, extrudeColor: '#000', extrudeDarken: 0,
        rot3dX: 0, rot3dY: 0, rotZ: 0, bendCurve: 0,
        glowSpread: 6, glowColor: 'rgba(255,255,255,0.8)',
        bannerColor: 'rgba(255,255,255,0.12)', bannerRadius: 14, bannerPadX: 24, bannerPadY: 10
    },
    comic_pop_3d: {
        name: '3D Comic Pop',
        category: 'Cartoon 3D',
        bitmask1: TITAN_TEXT_BITS.BOLD | TITAN_TEXT_BITS.ALL_CAPS | TITAN_TEXT_BITS.STROKE_ACTIVE | TITAN_TEXT_BITS.DUAL_STROKE | TITAN_TEXT_BITS.DROP_SHADOW,
        bitmask2: TITAN_TEXT_BITS.EXTRUDE_3D | TITAN_TEXT_BITS.OBLIQUE_MODE,
        fontFamily: 'Impact, "Arial Black", sans-serif',
        fontSize: 62, tracking: 2, lineHeight: 1.1,
        fillType: 'solid', fillColor: '#facc15',
        gradient: 'none',
        strokeWidth: 3, strokeColor: '#000000', dualStrokeWidth: 5, dualStrokeColor: '#ffffff',
        shadowBlur: 0, shadowColor: '#000000', shadowDist: 10, shadowAngle: 45,
        innerShadowBlur: 0, innerShadowDist: 0, innerShadowColor: 'transparent',
        extrudeDepth: 12, extrudeColor: '#000000', extrudeDarken: 60,
        rot3dX: 0, rot3dY: 0, rotZ: -5, bendCurve: 0,
        glowSpread: 0, glowColor: 'transparent',
        bannerColor: 'transparent', bannerRadius: 0, bannerPadX: 0, bannerPadY: 0
    }
};

module.exports = {
    PIXELLAB_PRESETS
};
